### ISSUE TITLE
Create DESeqDataSet from refine.bio TSV file

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#103]
This is related to #102 in my opinion.

For RNA-seq data where quantile normalization is skipped, we supply "bias corrected counts without an offset" in a TSV file. We can use this file with `DESeq2::DESeqDataSetFromMatrix()` and then have subsequent examples where we perform transformations, etc.

**Comment by cansavvy** [comment]
Been chatting with @jaclyn-taroni about this. I think we need to figure out a plan regarding how we are going to integrate DESeq2 steps with the RNA-seq modules that is a bit more widespread and should be more fundamental to this RNA-seq section overall than I originally thought. 

Here's some steps of how we integrate DESeq2 into our material: 

- The introduction to the RNA-seq section needs to include a brief introduction on `Why do we use DESeq2`. This would also probably include some context around when a user might not want to use DESeq2 (which we expect won't come up often but we should try to be prescriptive where we can. ) 
- We will need to include brief summaries with documentation links about the differences of DESeq2 normalization methods and refinebio's QN normalization. Each RNA-seq module should link back to this explanation. 
- Each RNA-seq module will need to choose whether or not to: 
   Option 1) Start with non-QNed data from refinebio which we turn into a DESeq2 object (I think this will be most modules) 
   OR
  Option 2) Download the already QN'ed data from refinebio and proceed with the data outside of DESeq2
We will have to discuss on a per module basis (on the respective issues) which option we are going for. I will try to post some initial thoughts and suggestions on this for these modules. 
- This also means the getting started sections of each module should reflect checking or unchecking the QN part of refinebio downloading.

**Comment by cansavvy** [comment]
Related to #136

**Comment by jaclyn-taroni** [comment]
Do we think we need to keep this open given the direction we've decided to go with all of the RNA-seq examples @cansavvy?

**Comment by cansavvy** [comment]
I suppose its covered in the DGE analyses as well as in the RNA-seq header section #125 where we can introduce the concepts.
