### ISSUE TITLE
[Investigation] How might we make a bookdown with Rmd chapters in multiple input folders?

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#107]
It was unclear to me how easy or hard this would be to make a bookdown by keep our current module per folder structure. 

Here's the relevant bookdown chapter
https://bookdown.org/yihui/rmarkdown/bookdown-project.html  

This issue made me think it wasn't very possible: https://github.com/rstudio/bookdown/issues/107

But these issues made me think it's more possible if we change the yml file: 
https://github.com/rstudio/bookdown/issues/418
https://stackoverflow.com/questions/40578609/set-r-bookdown-input-directory

**Comment by jashapiro** [comment]
Confirming that this is not as easy as I thought. While you can put rmd files in the subdirectories, they have to act as if they are in the main directory, as that is where they will render from. So separated chapter units are not really possible. 

This makes me sad.

**Comment by jaclyn-taroni** [comment]
Is there some non-bookdown, GitHub Pages alternative solution we should consider?

**Comment by jashapiro** [comment]
There is the builtin Rmarkdown sites: https://rmarkdown.rstudio.com/lesson-13.html

**Comment by cansavvy** [comment]
> Is there some non-bookdown, GitHub Pages alternative solution we should consider?

I think this partially depends on what other functionalities we want. For example, do we need/require it be able to be exported to a PDF as well?

**Comment by jaclyn-taroni** [comment]
I would need a more complete idea of functionalities we'd be losing to say for sure, but I feel that we do not need a PDF, specifically.

**Comment by cansavvy** [comment]
bookdown does give you a lot of control over aesthetics. Here's their own paragraph about "why bookdown": https://bookdown.org/yihui/bookdown/motivation.html

**Comment by cansavvy** [comment]
Is there a particular reason we wouldn't want to just use github pages?

**Comment by jaclyn-taroni** [comment]
> Is there a particular reason we wouldn't want to just use github pages with the Jekyll stuff like we are doing for training: https://alexslemonade.github.io/2020-june-training/

No, not necessarily. That's part of what we're trying to discover and is what I meant by https://github.com/AlexsLemonade/refinebio-examples/issues/107#issuecomment-655013580. #92 is sparse for a reason - it was just an idea.

**Comment by cansavvy** [comment]
Based on this discussion, I'm going to make a motion that we should stick with a simpler solution of using GitHub pages and maybe borrow some of the Jekyll functionality used on the `training-specific-template` repo. Will set up a new issue for this.
