### ISSUE TITLE
"Getting Started" section materials to be added to refinebio-examples book

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#109]
#### Background
In our goal of making our refinebio-examples more approachable, we'll need to add some content that equips users with some foundational knowledge. Here's a rough outline and some materials that we can borrow from: 
We should probably think about borrowing from the intro to R training-module where appropriate https://github.com/AlexsLemonade/training-modules/tree/master/intro-to-R-tidyverse
*This will need to get broken out into smaller issues as we decide what topics are needed in this section* 

#### Rough outline: 
- Getting Started
    - About refine.bio (link out to docs!) 
    - About how this tutorial book is structured (i.e. each analysis has its own somewhat repetitive info about getting started)
    - What you need to install to run the examples
         - Can borrow from: https://github.com/AlexsLemonade/refinebio-examples#general-requirements-for-the-example-workflows
   - How to get the data - this is still to be determined 
      - Might be able to borrow from, but will likely be very different: https://github.com/AlexsLemonade/refinebio-examples#how-to-use-this-repository.
    - How to use/get Rmds 
       - Should definitely link to: https://bookdown.org/yihui/rmarkdown/
- A quick primer on file paths and R
    - Borrow from: https://github.com/AlexsLemonade/training-modules/tree/master/intro-to-R-tidyverse where appropriate. 
- Resources for learning R

#### Resources we should link to
This getting started section should also include resources for people who may need more practice with the basics. Some suggestions:  
+ [Swirl, an interactive tutorial](https://swirlstats.com/)  
+ [R Markdown](http://rmarkdown.rstudio.com)  
+ [R for Data Science](https://r4ds.had.co.nz/)  
+ [Tutorial on R, RStudio and R Markdown](https://ismayc.github.io/rbasics-book/)  
+ [Handy R cheatsheets](https://www.rstudio.com/resources/cheatsheets/)  
+ [R Notebooks tutorial](https://bookdown.org/yihui/rmarkdown/)

**Comment by cansavvy** [comment]
I like the Hemberg lab's getting started. It tells you how to download the data and get the docker image if you want. Has some videos.  https://scrnaseq-course.cog.sanger.ac.uk/website/index.html#about-the-course

**Comment by cansavvy** [comment]
@dvenprasad , do you think you could look at this general outline and see if it fits your expectations of what kinds of material should be included as background information for the users at the beginning of the whole tutorial? This would be it's own larger section, before any of the analyses examples (#118), but then each analysis example itself will have its own getting started section which I'm workshopping over on #122 (using Clustering analysis to test it out.

**Comment by dvenprasad** [comment]
Yep the rough outline looks good. 🏆   Will take a look at #122

**Comment by cansavvy** [comment]
:thankyou:

**Comment by cansavvy** [comment]
Before we can merge #122 or associated upcoming PRs relating to #116, we need to figure out more specifically: 
- What info should we include in the Getting Started section vs analysis-specific "getting started"? What's the "Venn diagram" of these sections' materials look like?
- Related to this but stating the question in a different way: which bits in the overall getting started should we link to in the individual analyses' getting started?

I'm going to try to sketch this out and post here.

**Comment by cansavvy** [comment]
![IMG_2350](https://user-images.githubusercontent.com/23458084/87187806-c2bc1380-c2bb-11ea-918f-03d0dedf6e6b.jpg)

Here's my thought about overlap and links between the "getting started" overall and "getting started"-each analysis sections. Lines connecting means there should be a least a link connecting them. It may be as simple as "for more information see BLANK" Or we could link out the section entirely. Unsure at this point. We may be able to better determine this once we see what a rough draft of the Overall "Getting Started" section looks like. 
(A rough draft of the individual analysis "Getting started" is open on #122)

**Comment by cansavvy** [comment]
This can be closed since the main Getting Started section has been merged as of #138
