### ISSUE TITLE
Create microarray gene ID conversion example

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#113]
This is a parallel issue to #110 

The only module I'm seeing that has an RNA-seq example and not a microarray example is the gene ID conversion: ensembl-id-convert

I'm not sure that we will need to change it that much from the RNA-seq example except that it will need to be a different dataset.

**Comment by cansavvy** [comment]
Since this module of gene ID conversion won't depend on the gene expression data itself, we might consider a linking out approach like is decribed for the kegg pathway module: https://github.com/AlexsLemonade/refinebio-examples/issues/131#issuecomment-656716635

This may mean because we have microarray listed first, we need to switch the current gene ID conversion example to a microarray dataset and then link to that from RNA-seq.

**Comment by cansavvy** [comment]
So we can partially address: https://github.com/AlexsLemonade/refinebio-examples/issues/98 we should use a mouse dataset for this gene id conversion example.

**Comment by cbethell** [comment]
I filed a [draft PR](https://github.com/AlexsLemonade/refinebio-examples/pull/212) for this issue using a [mouse glioma cancer stem cell dataset](https://www.refine.bio/experiments/GSE13490/cancer-stem-cells-are-enriched-in-the-side-population-cells-in-a-mouse-model-of-glioma) with n = 15 samples (which has been uploaded to the S3 bucket for testing/review).

This produces a mapped data frame that looks like:
<img width="763" alt="Screen Shot 2020-09-10 at 8 19 51 AM" src="https://user-images.githubusercontent.com/43576623/92728456-be08ef80-f33e-11ea-85f2-496d709845a4.png">

If we want to stick with a smaller dataset, we could use this [transcription profiling of mouse glioma cell line dataset with n = 4 samples](https://www.refine.bio/experiments/E-MEXP-718/transcription-profiling-of-mouse-glioma-cell-line-grown-in-two-types-of-media-to-investigate-cell-de-differentiation), which would produce a mapped data frame that looks like:
<img width="364" alt="Screen Shot 2020-09-10 at 8 26 35 AM" src="https://user-images.githubusercontent.com/43576623/92728781-5dc67d80-f33f-11ea-993d-65fd8c9386d0.png">

Any ideas on what we think would work best in the case of this notebook?

**Comment by cansavvy** [comment]
I'm not sure that the screenshots you've included help me give useful feedback for these datasets. 
Instead, it might be more helpful if you included some summary stats. This may include (but doesn't have to be limited to);
- How many gene identifiers are mapped versus not mapped?
- How many multi mappings does each gene identifier have?

I think these are quick things that we may want to encourage our users to look into as well. For example, if nothing is mapping to your gene identifier, maybe you did it wrong or maybe you should use a different gene identifier OR maybe that's expected and its okay for your purposes, but its always good to be aware of how many genes you are potentially "losing" if you end up relying on this new gene identifier you've mapped to for your downstream analyses.

In regards to your general question about which dataset, I don't think sample size matters too much for gene identifier mapping, but I would we stick with the n = 15 set so we try to recommend datasets that might be useful for users in other contexts. Aka n = 4 is fine for what we are illustrating gene identifier mapping but not necessarily other common analyses, so might as well invest in a dataset that our users might find useful beyond this example (n = 15 isn't so big that this would be hindering memory wise either).

**Comment by cbethell** [comment]
> I'm not sure that the screenshots you've included help me give useful feedback for these datasets.
> Instead, it might be more helpful if you included some summary stats. This may include (but doesn't have to be limited to);
> 
> * How many gene identifiers are mapped versus not mapped?
> * How many multi mappings does each gene identifier have?
> 
> I think these are quick things that we may want to encourage our users to look into as well. For example, if nothing is mapping to your gene identifier, maybe you did it wrong or maybe you should use a different gene identifier OR maybe that's expected and its okay for your purposes, but its always good to be aware of how many genes you are potentially "losing" if you end up relying on this new gene identifier you've mapped to for your downstream analyses.
> 
> In regards to your general question about which dataset, I don't think sample size matters too much for gene identifier mapping, but I would we stick with the n = 15 set so we try to recommend datasets that might be useful for users in other contexts. Aka n = 4 is fine for what we are illustrating gene identifier mapping but not necessarily other common analyses, so might as well invest in a dataset that our users might find useful beyond this example (n = 15 isn't so big that this would be hindering memory wise either).

Of course, that makes sense! I will include said summary stats in the notebook (still using the n = 15 dataset) and ping you over on the draft PR once I commit those changes 👍  Thanks for the feedback @cansavvy!
