### ISSUE TITLE
Add template Rmd notebook to be used for new analyses

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#116]
Based on the conversation here #114 It sounds like each analysis should come with some introductory materials including but not limited to: 

- the goals of the analysis: what it is good for and not good for
- introducing the terms/concepts of the analysis
- the dataset they will be using for the example
- how they can change the analysis to fit a different dataset
- further resources for learning

I think what would make this easiest to "follow along" and/or allow participants to skip the "getting started" material is to have a parallel structure for each new analysis. I'm going to brainstorm on what this might look like and paste the ideas here.

**Comment by cansavvy** [comment]
I'm working on an example of what this might look like. Will post for feedback and then we can use it to build on to each analysis's notebook.

**Comment by cansavvy** [comment]
Need to revise the current rough draft to include links to the overall "Getting Started" section as described here:https://github.com/AlexsLemonade/refinebio-examples/issues/109#issuecomment-656827906

**Comment by cansavvy** [comment]
My thought is that if these modules are supposed to be able to be downloaded separately and used from there, then the links to the `Getting Started` section (#138) should _not_ be relative but instead be a github.io link.

**Comment by cansavvy** [comment]
This template will be an `.Rmd` that we can copy when making a new analysis!

**Comment by jaclyn-taroni** [comment]
The scope of this ticket should include adding information about the `.Rmd` template to `CONTRIBUTING.md`.

**Comment by cansavvy** [comment]
The main goal of this has been addressed.
