### ISSUE TITLE
Set up a navigation bar on github pages

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#118]
Related: https://github.com/AlexsLemonade/refinebio-examples/issues/107#issuecomment-655688144

I think the header on the top of the page would include the main technologies/ larger sections (see below).
I think we'd also include TOC on the side of the web page to allow for easy jumping around to different analyses modules for *within* that technology. 

#### Rough Outline
```
refinebio-examples
├── Getting_Started 
│   ├── What is refinebio?
│   ├── About how this tutorial book is structured
│   ├── What you need to install to run the examples
│   ├── How to follow these examples
│   ├── How to get the data
│   ├── How to use/get Rmds
│   └──A quick primer on file paths and R
├── RNA-seq
│   ├── Introduction to RNA-seq
│   ├── Gene ID conversion
│   ├── Clustering
│   └── ... rest of the analyses for RNA-seq
├── Microarray
│   ├── Introduction to Microarray
│   ├── analyses examples for microarray
│   └── ...
├── Advanced Topics
│   ├── Introduction to advanced topics
└── Compendium (eventually)
    └── ...
```

For some of these things, we might be able to borrow what Jackie figured out with Jekyll `training-specific-template` repo?
Once we get the basics done we could even prettify it so it matches refinebio aesthetics.

**Comment by cansavvy** [comment]
@dvenprasad What do you think about this idea?

**Comment by jaclyn-taroni** [comment]
(Josh not Jackie figured that out.)

**Comment by jashapiro** [comment]
I'll just chime in that getting the two navbars is not impossible (top and side), but will probably require dev time to make some template html. I couldn't find a prebuilt jekyll theme that did it, but it should be doable, and even possible to have the side navbar reflect the index as with `nb.html` files.

**Comment by jashapiro** [comment]
Oh, I should also caution that I seem to remember jekyll and .Rmd files not playing together as well as I liked. I did some odd hacking to make things go on my old website. https://github.com/jashapiro/jashapiro.github.io/blob/2f6391cd28f6eef3a79cb41450159fd104421d65/Rakefile#L63
Maybe things are better now, but another option worth looking at is `blogdown`/hugo, which can still put the rendered site on github pages as static files (and should be able to do all the templating).

**Comment by jaclyn-taroni** [comment]
Seems like it may be valuable to get a sketch of what we are looking for (ideally) as we do things like look into `blogdown`, etc. I imagine this will also help facilitate getting input from the dev and design teams as needed.

**Comment by cansavvy** [comment]
![IMG_2346](https://user-images.githubusercontent.com/23458084/87084964-14519900-c1fd-11ea-9b4e-b1c8dd0468b8.jpg)

This is not the best drawing, but basically the red letter on the side would change based on which section you are in and the table of contents for that section would be shown.
The blue lettering on top is how you can navigate between the technologies and Getting Started sections. 

Do people have suggestions/comments/questions?

**Comment by jashapiro** [comment]
Does the left sidebar select different pages, or jump to anchors on the same page? In other words, is RNA-seq one page with different sections, or more than one page?

If it is one page, I think this is fine. If there is more than one page per technology, I might suggest we should make the top nav dropdown menus, or with a second level of some kind.  Then we can reserve left nav for navigation/toc within pages, like with nb.html files. 

I'm curious to hear @dvenprasad's opinion, though.

**Comment by cansavvy** [comment]
> If it is one page, I think this is fine. If there is more than one page per technology

I also think one page per technology is fine , but we'd have to combine the nb.htmls in some way. But I also still want the Rmds to be separate for downloading purposes. (I don't know how this would work behind the scenes). 

>  I might suggest we should make the top nav dropdown menus, or with a second level of some kind.

I like the dropdown menus idea.

**Comment by dvenprasad** [comment]
What are the constraints for having a single nav bar on the side like a TOC?

**Comment by jashapiro** [comment]
What do you mean by "constraints"? My main thought was that we probably do want to have a TOC nav bar which handles within-page navigation (see [here](https://htmlpreview.github.io/?https://github.com/AlexsLemonade/training-modules/blob/2020-june/intro-to-R-tidyverse/01-intro_to_base_R.nb.html) for an example) but do we want that to be combined with larger site navigation?

I think it should be possible to do those as two separate nav systems, but integrating them may be tough. But that is me speaking as a non-dev...

**Comment by dvenprasad** [comment]
I see... Since the toc does not nest too much, it would be okay to have one main TOC style navigation on the side.

**Comment by dvenprasad** [comment]
Like this one here: https://scrnaseq-course.cog.sanger.ac.uk/website/biological-analysis.html#clustering-methods

**Comment by cansavvy** [comment]
We should be able to set up these navbars using a thing that @jashapiro found in the rmarkdown docs

> In the help for rmarkdown::html_document, I found this: Navigation Bars
If you have a set of html documents which you’d like to provide a common global navigation bar for, you can include a “_navbar.yml” or “_navbar.html” file within the same directory as your html document and it will automatically be included at the top of the document.
The “_navbar.yml” file includes title, type, left, and right fields (to define menu items for the left and right of the navbar respectively). Menu items include title and href fields. For example:
title: "My Website"
type: default
left:
  - text: "Home"
    href: index.html
  - text: "Other"
    href: other.html
right:
  - text: GitHub
    href: https://github.com

I tried this out on #150 but it currently is not working, but I'm noting it here because it is most related to this issue and there should be a way to fix it.

**Comment by jashapiro** [comment]
Candace connected this, but I'll just make the connection more explicit here... I made an example of one way to accomplish the 2 navbar idea in #161. A rendered example is here: https://htmlpreview.github.io/?https://github.com/AlexsLemonade/refinebio-examples/blob/jashapiro/navbar/01-getting-started/getting-started.html

To implement this most easily (using relative paths), we would probably want to remove subdirectories from the overall structure: all notebooks for microarray analysis would be housed in the `02-microarray` directory, for example, rather than in separate subdirectories. We could then have a single shared `data` subdirectory, (and `results`, `plots`, etc.). We could either be careful about file names to not clobber data files from other notebooks, or use subdirectories within `data/` to separate (the inverse of the current structure, basically, with `data/clustering`, `data/differential-expression` etc.).

If every notebook is one directory deep, then we could use a shared `_navbar.html` file, symlinked to each subdirectory. Alternatively, we could keep separate `_navbar.html` files for each subdirectory, which could allow us to have the microarray section expanded when in a microarray notebook. While this seems appealing, it would be much more work, as every navbar file would have to be separately maintained, or some clever script written to keep things in sync.

**Comment by cansavvy** [comment]
I think originally we kept each notebook in its own folder in case we went with the download zip strategy See #100 
But now that we have instructions for users to set up their own directory (with some chunks to do it for them and check #146 ) I think the subdirectories are less necessary. So I'm not opposed to ditching the subdirectory folders and moving to one `data/` folder per section e.g. `02-microarray`. But this is probably a good time to decide this type of thing before we start adding more analyses.

**Comment by cansavvy** [comment]
I like the navbar on #161 I think it will help users navigate around. I think beginning of next sprint we will be ready to start implementing it. @jashapiro Do you have thoughts on how to add this to either the Snakefile or render-notebooks.R script? I can try to work on this next week after #171 is resolved.

**Comment by jashapiro** [comment]
Adding the navbar to the Snakefile is covered in #161. It is a pretty simple change: https://github.com/AlexsLemonade/refinebio-examples/blob/ef4309144c9d1ec951ef0b8ad87d303500ea505f/Snakefile#L5-L9
