### ISSUE TITLE
Create UMAP dimension reduction example with RNA-seq data

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#128]
Related to #110 

Currently we have a microarray example of UMAP. We should be able to largely copy the microarray example but switch out the dataset and the accompanying wording. 

Ideally we will use the same dataset as we will use for PCA RNA-seq example (#129) and ideally the dataset will not have too skewed of a global structure. 

This can be done separately from the "getting started" additions to each analysis #116

**Comment by cansavvy** [comment]
I don't think there's a handy UMAP DeSEq2 function. I can see two different strategies for this example. We could use this as an opportunity to show how to extract a matrix from a DESeq2 object. So the steps would be: 

Non-QN'ed data -> DESeq2 object -> `assay()` to extract normalized data as matrix -> UMAP.

**Comment by cansavvy** [comment]
I think we want to use the same dataset and general steps as we end up using the PCA module (#32 ) (For the plot, let's do the 0 label, 1 label, 2 labels bit again). But the main difference is we will also need discuss being cognizant of parameter selection (which wasn't as necessary for PCA). 

We can borrow some descriptions from https://github.com/AlexsLemonade/training-modules/blob/ddc9c76e03aaf147fb2f011490ea6aec835de064/scRNA-seq/05-dimension_reduction_scRNA-seq.Rmd#L254

But I think for the purposes of. keeping notebooks short, we won't explicitly go through the parameter "experiment" bit. Instead we can just include some of the words and guidance about parameters and steer them to helpful resources for UMAP interpretation/parameter selection.

**Comment by cbethell** [comment]
In starting to get the notebook ready for this issue, I wanted to post an outline of the plan going forward:

1. Read in `DESEq2` and `uwot` packages (discussed using the `umap()` function from `uwot` with @jaclyn-taroni)
2. Import and set up data - use same large non-QN’ed dateset as in PCA example notebook in PR #176
3. DESeq2- Create a `DESeqDatatset` object, define minimum counts cutoff, use `vst()` for normalization
4. Use `assay()` to extract the normalized data and run `uwot::umap()` 
5. Plot using `ggplot()` — adding annotation labels one by one starting with 0 labels
6. Add resources (some borrowed from https://github.com/AlexsLemonade/training-modules/blob/ddc9c76e03aaf147fb2f011490ea6aec835de064/scRNA-seq/05-dimension_reduction_scRNA-seq.Rmd#L254) re the UMAP interpretation/parameter selection as noted in [@cansavvy's comment above](https://github.com/AlexsLemonade/refinebio-examples/issues/128#issuecomment-674839944)

**Comment by cansavvy** [comment]
Sounds good to me!

**Comment by cansavvy** [comment]
> 1. Read in `DESEq2` and `uwot` packages (discussed using the `umap()` function from `uwot` with @jaclyn-taroni)

What was the rationale for switching to `uwot`? Is this so it matches what `calculateUMAP()` function in scater uses and/or because it returns a matrix by default instead of a list? 

I think my only problem with it is it doesn't carry over dimension names which means we need to "trust" that all the coordinates are in the same order. This is may be fine, but I don't like to encourage our users to bind columns blindly. 

Both `umap::` and `uwot::` claim to be using the same algorithm from the McInnes & Healy, 2018 paper, so if we are not too attached to `uwot`, then I prefer `umap::` so we can have our users bind by matching back accession codes rather than getting a label-less matrix. 

If we do need to use `uwot` we need to figure out if we can have it return names to us. There are some [additional arguments that have it spit back more info](https://rdrr.io/cran/uwot/man/umap.html), but it doesn't appear (in my brief look) that this includes dimension names from the original input. We can also experiment with maybe for some reason it likes the dimension names given to it a different way?

**Comment by jaclyn-taroni** [comment]
I suggested it because the documentation is better (IMO), which is not insignificant! This seems like too deep a rabbit hole to go into for this particular context, so why don't we use `umap::umap()`.
