### ISSUE TITLE
Create Kegg Pathway RNA-seq example

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#131]
Related to #110 

This can be done separately from the "getting started" additions to each analysis #116 

I don't remember enough about this analysis to say what kind of datasets we need... Will write more later.

**Comment by jaclyn-taroni** [comment]
If you're referring to the KEGG ortholog mapping example specifically, I don't think this needs to be in both places - it doesn't use any expression data as far as I can tell/remember. You could put a single example in whatever technology is presented first and link from the pathway analysis example(s) in the technology that is presented second.

**Comment by cansavvy** [comment]
This issue is being replaced by a broader issue #190
