### ISSUE TITLE
Create ssGSEA pathway analysis example with RNA-seq

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#135]
Related #110

**Comment by cansavvy** [comment]
This can built off of the new workshop material: https://github.com/AlexsLemonade/training-modules/blob/master/pathway-analysis/02-gene_set_enrichment_analysis.Rmd

**Comment by jaclyn-taroni** [comment]
That notebook is GSEA material. This issue tracks ssGSEA (could sub GSVA).

**Comment by jaclyn-taroni** [comment]
Side note: I would probably add a GSEA preranked issue that does use that material!

**Comment by cansavvy** [comment]
This issue is being replaced by a broader issue #190
