### ISSUE TITLE
Analysis Updates: RNA-seq differential-expression module 

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#137]
Since we are trying to integrate more DESeq2 functionality into our RNA-seq section, we should make differential expression reflect that as well since that is its main utility. 

We can borrow from training-modules steps: https://github.com/AlexsLemonade/training-modules/blob/master/RNA-seq/05-nb_cell_line_DESeq2.Rmd and maybe useful tidbits from here: https://github.com/AlexsLemonade/training-modules/blob/master/RNA-seq/03-gastric_cancer_exploratory.Rmd

<del>I'm debating about whether we should still maintain a QN'ed from refinebio version of differential-expression? One strategy is we could keep the current example but reframe it as a "pre-normalized DE" example and make the new notebook a "starting at counts DE" example. Thoughts? </del>

**Comment by jaclyn-taroni** [comment]
The current example isn't QN'd data.

**Comment by cansavvy** [comment]
Oh I see that now. Hmm.. I guess I was thrown off by DGEList thing. Why did we choose limma-voom here?

**Comment by jaclyn-taroni** [comment]
I do not have a good reason.

**Comment by cansavvy** [comment]
We should look at the examples listed here and decide what we would like to do (or maybe a few of them): https://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html#Downstream_DGE_in_Bioconductor

I do not understand the rationale of limma-voom vs the various DESEq2 models and I suspect this will also be an area of confusion for our users. 

So although we don't want to get too far into the weeds on dge models, we should evaluate: 
- what steps we are recommending
- why we are recommending them (when might they not be a good idea)
- and how this might fit in with the new RNA-seq modules being added (#110)

**Comment by cansavvy** [comment]
I think I remember reading this before, but it's a great little summary to keep in mind for this: https://www.biostars.org/p/284775/

**Comment by cansavvy** [comment]
Also this by Mike Love: https://mikelove.wordpress.com/2016/09/28/deseq2-or-edger/

**Comment by cansavvy** [comment]
I don't feel like its super necessary or helpful to keep an example of each edgeR, limma-voom, and DESEq2. So what I think might be a good way forward is to change this example to be DESEq2-centric, but briefly acknowledge the others and link out to examples of those as well as the nice summary articles. 

Our rationale for choosing DESeq2 would basically be 
- Other methods are all about as good for normalization purposes
- It has a lot of nice docs and examples
- Be honest: we have preferences. 

So the current rna-seq_DGE.RMd notebook we we switch the strategy to DESeq2 so it will be more parallel to the rest of of module changes. Basic steps would be: 
1) Download non-QN'ed refinebio data 
2) Create DESeq2 object: DESeq2::DESeq2::DESeqDataSetFromMatrix() (Side note maybe show how to save it to an RDS) where `design = ~ mutation.status`. 
3) Follow the modeling set up steps not unlike: https://github.com/AlexsLemonade/training-modules/blob/master/RNA-seq/05-nb_cell_line_DESeq2.Rmd
4) Keep a volcano plot. Add some interpretation bits. 
5) At the end link to heatmap clustering example because that flows nicely.

**Comment by cbethell** [comment]
As discussed with @jaclyn-taroni and @cansavvy in the data science team Slack channel.

The changes made in PR #140 seem to be better suited for the differential-expression example notebook. That being said, the current branch in PR #140 (which has been reverted into a draft PR and will be left as such until this ticket is closed) can be merged into a new branch for the purpose of getting started on this ticket.

**Comment by jaclyn-taroni** [comment]
Expanding on this point a bit - from https://github.com/AlexsLemonade/refinebio-examples/pull/140#pullrequestreview-459609826

> What if instead we used much of what we have here (e.g., the dataset and collapsing steps) as a DGE example? We could have multiple RNA-seq DGE examples that vary in designs and this dataset could be an example of collapsing replicates and multifactor designs. If it is presented that way, I would be less concerned about the extent of the metadata cleaning steps required, too.

So more generally, I think _multiple_ DGE examples could be very useful where what is on `cbethell/add-clustering-rna-seq-example` is **not** the first example is presented. I expect that putting multiple examples into the same notebook is going to make an individual notebook pretty _long_, which is to say that I think there will be multiple `differential-expression` notebooks and what's on that branch will be `02` or later.

**Comment by jaclyn-taroni** [comment]
I also wanted to note that the dataset currently in use on #140 is also included in [one of our exercises for training](https://github.com/AlexsLemonade/exercise-notebook-answers/blob/32a3f211aae6e4b5675e87bf7c067d06721ab831/pathway-analysis/prep/01-prepare_medulloblastoma_pdx.Rmd)–I expect that material will also help with getting the DGE example done.
