### ISSUE TITLE
Create a style/contributing guide for this repo

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#144]
Talked to @jaclyn-taroni this morning about figuring out standard styles for our refinebio-examples. 
A style guide might be a good way to standardize this. We can use this for reference as we continue to add/revamp material. 

Things to be addressed by a style/contributing guide. 
- Formatting of typical words/items:
    - "refine.bio" or "refinebio"
    - `.Rmd` vs Rmd vs .Rmd
- What should the notebook headers look like? 
- Should sections be numbered? 
- Should links always go to the online version of the book? (I think yes) 
- Chunk naming? 

There will be more things we need to add to this style guide, but I cannot think of them as now.

**Comment by cansavvy** [comment]
Should this stay on an issue as to not clutter up the repo that users might download? Or do we just assume they probably won't look at it?

**Comment by jaclyn-taroni** [comment]
I think it should be added as `CONTRIBUTING.md` - my suspicion is that most people will download a single notebook at a time and it won't matter.
