### ISSUE TITLE
Create custom rendering script

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#149]
To make citations render correctly, `pandoc` needs a `bibliography:` specification. However, if the user downloads the `Rmd` on their own to run and does not have the file specified by `bibliography:` , `pandoc` fails to render. See the error and more discussion over here: https://github.com/AlexsLemonade/refinebio-examples/pull/148#issuecomment-669170681

The work around we've come to as of now is to make all refinebio-examples notebooks be called by a custom rendering script that will add on the `bibliography:` script upon rendering. This will leave the `.Rmd` files ready for download and easy use without a `.bib` file. 

Talking to @jashapiro to complete this add on to the `.Rmd` header chunk, we can borrow aspects from `exrcise` package code: https://github.com/AlexsLemonade/exrcise/tree/master/R
and ultimately use the `render` command: https://rmarkdown.rstudio.com/docs/reference/render.html

The script would look something like: https://github.com/AlexsLemonade/training-modules/blob/master/scripts/make-live.R

The usage of this will also need to be documented in the (currently WIP #148) CONTRIBUTING.md

**Comment by cansavvy** [comment]
@jashapiro 's advice I'm posting here: 
> I think the easiest way to do it will be to add the bibiliography right at the top of the yaml file. So you would find the first `---` (which should be the first line) and insert the bibiliography line there. Make a tempfile, then use `rmarkdown::render()` with an `output_file` having the appropriate file name.

**Comment by jashapiro** [comment]
The script should also use `rmarkdown::render(file, output_format="html_document")` To override the setting of `html_notebook` in the file's YAML. This is mostly so it doesn't embed the `.Rmd` file, which will not work without the associated `.bib` file.

**Comment by jashapiro** [comment]
> The script should also use `` To override the setting of `html_notebook` in the file's YAML. This is mostly so it doesn't embed the `.Rmd` file, which will not work without the associated `.bib` file.

On further investigation, you will probably want:
```
out_form <- rmarkdown::html_document()
rmarkdown::render(file, output_format = out_form)
```
as `rmarkdown::html_document()` will allow you to specify things like TOC options and `number_sections`, which probably will not carry over from the header `html_notebook` settings.
