### ISSUE TITLE
Run `styler` with GitHub Actions

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#154]
In #153, one of the checklist items being added is:

> * [ ] Run [r-lib/styler package](https://github.com/r-lib/styler)

I think we could use GitHub Actions for linting. I found this example in the `r-lib/actions` repo: https://github.com/r-lib/actions/tree/master/examples#when-it-can-they-be-used

**Comment by jashapiro** [comment]
This could also potentially be incorporated into the `render-notebooks` script and/or `Snakefile`? I had already mentioned running doctoc as part of that workflow (though I am not fully sold on doctoc for this, tbh as I tend to think it is redundant with the TOC Rmarkdown generates).

**Comment by jaclyn-taroni** [comment]
One general question before I disappear for a few days - could the scope of this issue then be run the `Snakefile` upon commit and push back to GitHub? That would probably be pretty handy, but some problems with that are run time, environment, and all the data files. (These may be prohibitive problems!) 

To the last point -- data files -- solving that issue such that there is a centralized place _we_ store the datasets for development could be pretty useful. My impression is that the workflow now if you are reviewing someone's PR or you have to work on a module you haven't worked on before, you have to go to refine.bio yourself and wait to get the dataset download. (Please tell me if that impression is wrong.) This seems like this could be a significant point of friction during development once we have the number/scope of modules that I think we will have by the time all is said and done. We also expect some development in the materials before we have the intro stuff cemented, so I think considering how can we make doubling back easier if you're not the person who wrote the analytical code for a notebook is worth a think. (S3?)

If you all think these ideas have some merit, please feel free to close this now that the `styler` step is in `render-notebooks.R` (#153) and file issues for Snakemake upon commit and centralized data files for development!

**Comment by cansavvy** [comment]
Wrote the remaining data question here on its own issue on #162 Closing this now.
