### ISSUE TITLE
Contributing guidelines: Sentences in Rmd

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#155]
Do we want to use "word wrap" – where the 80 character line limit is respected outside of code chunks – or semantic line feeds (one sentence per line)?

**Comment by cansavvy** [comment]
Hmm what's easier for people to read off line in the Rmds? Probably semantic and start new line after 80?

**Comment by jaclyn-taroni** [comment]
@jashapiro has convinced me that start new line after 80 is unnecessary for readability and it has always been a pain to format if you're rewriting a sentence!

**Comment by jashapiro** [comment]
> @jashapiro has convinced me that start new line after 80 is unnecessary for readability and it has always been a pain to format if you're rewriting a sentence!

The reformatting is my main annoyance, to be sure, but part of it was also that 80 is too wide for screencasting Rstudio, so you end up with funny line breaks anyway in that situation. 

Personally, I'd be happy enough with 1 line per paragraph (with soft wrap, of course!) but that isn't as nice for source control. OSPL is a reasonable compromise.

**Comment by cansavvy** [comment]
I wonder if styler can do this automatically for us. I will look into that. Related to #154

**Comment by cansavvy** [comment]
So one sentence per line?

**Comment by jaclyn-taroni** [comment]
One sentence per line works for me 👍

**Comment by cansavvy** [comment]
I added a blurb about this in #146
