### ISSUE TITLE
How are we managing dependencies during development?

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#157]
In filing #154, I was taking a look at the `r-lib/actions` repository. One of the examples is a Docker-based workflow: https://github.com/r-lib/actions/tree/master/examples#docker-based-workflow

I'm not sure if we want to use a Docker image as part of a GHA workflow (we could!), but we have used them as part of development in the past so everyone has a consistent environment. A consistent environment would guard against code that is incompatible across different modules and we could probably include a list of all the packages and versions in Getting Started (related: #138).

**Comment by jashapiro** [comment]
Another option to keep in mind: 
https://blog.rstudio.com/2019/11/06/renv-project-environments-for-r/

Controversial related suggestion: move development/testing for this package to R 4.0. That is what new users will get, so it might make sense for this repo.

**Comment by cansavvy** [comment]
I had the thought about a docker image for this repo occur to me. Mainly for development now but we could also eventually have it available for the advanced topics type user.

**Comment by jaclyn-taroni** [comment]
Not controversial to me - the move to R 4.0 makes a lot of sense here!

**Comment by cansavvy** [comment]
Now that we have a Dockerfile #159 merged, the next question before being able to wrap up this issue is do we want to integrate into a GitHub actions workflow? Or just use it for development as usual? See the current instructions about Docker in https://github.com/AlexsLemonade/refinebio-examples/blob/master/CONTRIBUTING.md#docker-for-refinebio-examples

**Comment by cansavvy** [comment]
I've added some more proposed procedures about Docker on #167. I think we can probably forgo the GitHub actions idea of Docker as of now (unless there are objections).
