### ISSUE TITLE
Create Docker image for development

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#158]
Related to #157, while we are already going to be revamping each analysis and adding new ones, this is the best time to create a Docker image for this repo for development. 
This would help us manage dependencies have more consistent environments. Also in our efforts to make styler automatic, we can set it up in a Docker image as well. 

Some requirements we know of so far for this Docker image (this list is not at all complete - part of the reason we should build this Docker image as we go along): 
- R version 4.0 
- Tidyverse 
- devtools
- styler  - This should also allow us to automatically set `use_tidy_style()` before development so when it is called by the `render-notebooks.R` it will be styling consistently. 
- snakemake
- ComplexHeatmap

**Comment by cansavvy** [comment]
The bioconductor package installation problems on OpenPBTA noted here: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/691
Are also relevant here, yes? So we should similarly use that install_bioc.R script in our docker image here.

**Comment by jashapiro** [comment]
> The bioconductor package installation problems on OpenPBTA noted here: [AlexsLemonade/OpenPBTA-analysis#689](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/689)
> Are also relevant here, yes? So we should similarly use that install_bioc.R script in our docker image here.
I think this is less of an issue here. I don't think we care as much about long-term stability as consistency across developers.

**Comment by cansavvy** [comment]
Okay. I've got a basic docker image underway (Will PR it soon). What we will later need to answer is where we want to store it on docker hub. 

Presumably we store it somewhere with ccdl images and it would be something like: `ccdl/refinebio-examples`.

**Comment by cansavvy** [comment]
Also obviously this issue can't be closed before CONTRIBUTING.md is updated to reflect Docker image usage. (And some of that is still at large #157 )

**Comment by cansavvy** [comment]
Forgot this should remain open, until we push the image to Docker Hub. I currently don't have permission (said `denied`) to push the image to `ccdl` (and I am presuming this is where we want it).

**Comment by cansavvy** [comment]
It's alive! Docker image for this repo is now able to be pushed and pulled from `ccdl/refinebio-examples` and can be updated there as well. 

We do not need admin powers to push updates from now on but did need to borrow @kurtwheeler 's admin powers to start the repo.
