### ISSUE TITLE
[Discussion] Get rid of subdirectory folders? 

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#163]
Some discussion here about READMEs: https://github.com/AlexsLemonade/refinebio-examples/issues/141#issuecomment-671995996 and here about `_navbar.html` files: https://github.com/AlexsLemonade/refinebio-examples/issues/118#issuecomment-671982097 suggests we should have a larger discussion about the idea of getting rid of subdirectories (aka 02-microarray contains all notebooks, no `clustering` directory. And one data folder per tech section). 

The goal of "each notebook can be self-contained" and implementation (#146) of also kinda means the subdirectories are less useful than they were when we began. 

This is probably a good time to decide this type of thing before we start adding more analyses.

Originally we kept each notebook in its own folder in case we went with the download zip strategy (See #100).
But now that we have instructions for users to set up their own directory (with some chunks to do it for them and check #146) I think the subdirectories are less necessary.

**Comment by cansavvy** [comment]
The `plots/` and `results/` folders would also have to be split up by dataset subdirectory folders which means we might have the current folder set up strategy in (#146) would be good for offline use, but if someone does end up downloading the whole repository (or when we are working with the whole repository for developing material).

**Comment by cansavvy** [comment]
A plus side is we would only need one "screenshots" folder: https://github.com/AlexsLemonade/refinebio-examples/pull/151#issuecomment-672036546

**Comment by jashapiro** [comment]
> A plus side is we would only need one "screenshots" folder: [#151 (comment)](https://github.com/AlexsLemonade/refinebio-examples/pull/151#issuecomment-672036546)

I am worried about the screenshots folder, as it does violate our "just download the RMD" idea. Can we use an abbreviated set of instructions in the templates that don't include screenshots?

**Comment by cansavvy** [comment]
> > A plus side is we would only need one "screenshots" folder: [#151 (comment)](https://github.com/AlexsLemonade/refinebio-examples/pull/151#issuecomment-672036546)
> 
> I am worried about the screenshots folder, as it does violate our "just download the RMD" idea. Can we use an abbreviated set of instructions in the templates that don't include screenshots?

You can't see the screenshots in the unrendered version anyway which is what a user would be working from anyway.

**Comment by cansavvy** [comment]
>  Can we use an abbreviated set of instructions in the templates that don't include screenshots?

Can you tell me more about what this would look like? The screenshots show users how to download data so this affects (#100)

**Comment by cansavvy** [comment]
URLs! Should have thought of that before!

**Comment by jashapiro** [comment]
> You can't see the screenshots in the unrendered version anyway which is what a user would be working from. It's only pertinent for view online rendered versions.

Also when they try to render a preview of the notebook. (URLs are a good solution!)

**Comment by cansavvy** [comment]
I think moving to this structure will also be easier for making a data download for development purposes more manageable (#162).

**Comment by cansavvy** [comment]
This has been discussed.
