### ISSUE TITLE
Add in a removable step to the getting started section which shows users how to get RNA-seq data with QN skipped

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#172]
Related: https://github.com/AlexsLemonade/refinebio-examples/issues/136#issuecomment-673489252

Often in the RNA-seq section examples, we will want our users to start off with non-QN'ed data. But our current "getting started" in the analysis section does not account for that or tell them to do that (whoops).  

This instruction step needs to be added in to the `Obtain the dataset from refine.bio` section and it should be put in `{{ }}` with a note above that tells us to delete it if we DO want QN'ed data. 
It should include a screenshot showing the button on refine.bio that gives them non-QN'ed data. 

This should be added to the template.Rmd file as well as the rna-seq clustering section where we will want Non-QN'ed data.

**Comment by cbethell** [comment]
I can get started on this issue 👍
