### ISSUE TITLE
Which analyses can use the same steps across technologies?

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#175]
For example, for analyses that the only input is a gene list (https://github.com/AlexsLemonade/refinebio-examples/issues/131 Like the KEGG pathway) there's no reason a user can't follow the same instructions for either microarray or RNA-seq. 

In these instances, we should place the analysis notebook that is more relevant (if there is one that is more relevant) and then link out the material to the other one. 

This issue is for keeping track of which analyses we think are transferrable across technologies so we know to make some sort of link out to it. Perhaps a brief document that just introduces the concepts and links to the other one? 

- KEGG pathway 
- Gene id conversion 
- ORA pathway analysis

**Comment by cansavvy** [comment]
Related #113

**Comment by cansavvy** [comment]
For these modules (and more that we will identify) we need to figure out how exactly we want to link a "cross-technology-compatible" example. 

I think we still should have a placehold `.Rmd` file for it, but the `.Rmd` basically just has a link to the other section's example?

**Comment by jaclyn-taroni** [comment]
Quoting myself from #102 

>  Specifically, duplicating analysis types like gene identifier conversion across separate microarray and RNA-seq "tracks" allows for some repetition of concepts and more opportunities to vary things in a way that supports learning (e.g., use different species [#98]).

Why not write two examples with a bit of variety?  With

> KEGG pathway

specifically, I believe you're referring to ortholog mapping for non-human species. We'll probably just use [`msigdbr`](https://cran.r-project.org/web/packages/msigdbr/index.html), instead, when it comes to addressing pathway analysis.

**Comment by cansavvy** [comment]
So I think it sounds like in these instances we have a duplicate example (with a different dataset), but try to make it a bit different than the other techhnology's example; each should cover a different instance (different species/gene id/etc). 

But then we can leave a note to users explaining that the steps for microarray/RNA-seq are pretty interchangeable, so if you want to see a similar example go to <this_link_to_the_other_sections_example>

**Comment by jaclyn-taroni** [comment]
> So I think it sounds like in these instances we have a duplicate example (with a different dataset), but try to make it a bit different than the other techhnology's example; each should cover a different instance (different species/gene id/etc). 
> 
> 
> 
> But then we can leave a note to users explaining that the steps for microarray/RNA-seq are pretty interchangeable, so if you want to see a similar example go to <this_link_to_the_other_sections_example>
> 
> 

This plan sounds good to me!

**Comment by cansavvy** [comment]
I think since this discussion has wrapped up and been spread out to its pertinent issues, it can be closed.
