### ISSUE TITLE
Simplify differential expression analysis

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#18]
As noted in https://github.com/AlexsLemonade/refinebio-examples/pull/6#discussion_r219489521, the experiment selected for differential expression analysis (same used one in `compare-processing`) has two factors: time point and genotype. These two factors are not taken into account in the differential expression example. We should pick a "simpler" experiment (e.g., single factor like treatment) for our differential expression analysis example.

**Comment by cansav09** [comment]
Closing issue. This was addressed by PR #22
