### ISSUE TITLE
Docker hub: latest doesn't mean `latest`

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#185]
@jashapiro found that the `latest` tag doesn't actually have default behavior that means its the `latest` version of the docker container when you pull it from the Docker hub. 

This is not what I thought the behavior for Docker hub was, so we need to switch strategies for Docker hub on this repo. 
I need to change this on CONTRIBUTING.md. 

We will make things simple. No tags, just keep pushing updated versions.

**Comment by jaclyn-taroni** [comment]
When we make that change, can we put all information for Docker under the same header? E.g., move `Docker image management` under `Docker for refinebio-examples`.

**Comment by jaclyn-taroni** [comment]
Information-only aside: this behavior is why we push to a specific tag for a training workshop (e.g., `2020-july`) and retag that same image with `latest` and push that – folks may accidentally pull without a tag and get something they don't want without the second retagging step!
