### ISSUE TITLE
Discussion: Consolidate "new notebook" instructions

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/refinebio-examples#186]
When adding a new example notebook, there are now a few steps that need to be followed in addition to (before?) starting the main work of filling its contents.

- A file name needs to be chosen
- Add the expected output html file to snakemake
- Add a link to the html file to `_navbar.html` (with a short title)
- Data may need to be added to S3
- other stuff I am missing?

Should these be added to the PR template? Or maybe just a consolidated section of CONTRIBUTING.md (or both?).

**Comment by cansavvy** [comment]
I can make an abbreviated version of the "adding a new analysis" section some place (wherever is helpful). 

These items are in the PR template as of now (along with other CONTRIBUTING.md related things):
>Add the expected output html file to snakemake
>Data may need to be added to S3

This has not been added yet. 
> Add a link to the html file to _navbar.html (with a short title)

This is explained in CONTRIBUTING.md but not a bullet point per se. 
>A file name needs to be chosen
