### ISSUE TITLE
Create images specifically for "How to Run This Example"

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#199]
We have images that are included in the template for every analysis.

The image for the download structure appears to be a cropped version of something we include in our docs: ![](https://github.com/AlexsLemonade/refinebio-examples/raw/a6ee8c92038972d990d3009f870a18e90ab3819d/template/screenshots/download-folder-structure.png)

Where there is extraneous information on the left hand size because that was illustrating a multiple experiment download.

And this is a screenshot on Mac for the analysis folder structure:

![](https://github.com/AlexsLemonade/refinebio-examples/raw/a6ee8c92038972d990d3009f870a18e90ab3819d/template/screenshots/analysis-folder-structure.png)

Where there is extraneous information at the top of the screenshot. It seems like we would benefit from using a consistent set of images that only illustrate the points we are trying to make and are as OS-agnostic as possible.

**Comment by dvenprasad** [comment]
I can whip up folder structures, no issues.

But I am torn between having screenshots make it feel "real" and "comfy" vs using folder structures diagrams. It is better for maintenance to use a folder structure diagram, so it is generic across the examples. Will do this and post them here.

**Comment by dvenprasad** [comment]
![examples-analysis-folder](https://user-images.githubusercontent.com/15315514/95382705-0ffa5200-08b8-11eb-9070-ccabbc2f8a9c.png)
![examples-download-folder](https://user-images.githubusercontent.com/15315514/95382707-1092e880-08b8-11eb-980f-da1efbd1df36.png)


Let me know if this accurate/ if you need me to resize the images. 
@cansavvy

**Comment by cansavvy** [comment]
These look awesome! I think they should be fine!

**Comment by cansavvy** [comment]
Next step is to search and replace in the project where these old versions of these images are and replace them with these.

**Comment by jashapiro** [comment]
Can't we just replace the files, giving them the same names?

**Comment by cansavvy** [comment]
> Can't we just replace the files, giving them the same names?

No, because it was your idea to tie images to a specific commit. (But yes we still keep the same file name, we still have to search and replace the commit though).

**Comment by jashapiro** [comment]
Oh yeah. 😁 I forgot that we are keeping downloads to single file...

**Comment by jaclyn-taroni** [comment]
⚠️  w   e   i   r   d      u   s   e      c   a   s   e  ⚠️
