### ISSUE TITLE
Be consistent about `library(ggplot2)`

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#211]
I think so far I might have been inconsistent and sometimes use `library(ggplot2)` and sometimes `ggplot2::` all the way through. 

For most packages, I am okay with us deciding on a case-by-case basis and sort of naturally showing `::` and `library()` 'out in the wild'. I also do NOT like loading the entire `tidyverse` because of how many things that includes. 

However, I think `ggplot2` is a special case because one ggplot requires you repeat `ggplot2::` a zillion times and plots are something I suspect users will often want to play around with the most and they may find the number of times they have to write (or forgot to write) `ggplot2::` burdensome. 

Because of this, I think we should change any notebooks we have already done that used the `ggplot2::` strategy, and change them to `library(ggplot2)`.

**Comment by jashapiro** [comment]
Worth adding that unlike `dplyr`, this does not tend to introduce any weird conflicts with base R, and `ggplot2` commands and syntax are pretty recognizable so that this should not be confusing.
