### ISSUE TITLE
"Modernize" the reshape2::melt step in the microarray gene id conversion notebook 

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#224]
It looks like `reshape2` is used by gene-id-annotation_microarray_01_ensembl.Rmd but was not added to the Dockerfile and image in that PR: #212 . 

Unless you install the `reshape2` package on your Docker container, snakemake will not successfully run. Apparently only `reshape` is included in the tidyverse set of packages?

<del>
- `if` install step should be added to this Rmd for the users purposes. 
- `reshape2` should be added to the Dockerfile. 
-  The Docker image should be rebuilt from that Dockerfile and pushed to dockerhub. </del>

#### Update : 
We should use the [strategy used in the RNA-seq gene id conversion notebook](https://github.com/AlexsLemonade/refinebio-examples/pull/218#discussion_r492054749) in the microarray notebook : 
https://github.com/AlexsLemonade/refinebio-examples/blob/8a2c52cc7e7b455f941e1416e8ae75165ec95690/02-microarray/gene-id-annotation_microarray_01_ensembl.Rmd#L258

**Comment by jaclyn-taroni** [comment]
Is this an opportunity to modernize instead? https://github.com/AlexsLemonade/refinebio-examples/pull/218#discussion_r492054749

**Comment by cansavvy** [comment]
> Is this an opportunity to modernize instead? [#218 (comment)](https://github.com/AlexsLemonade/refinebio-examples/pull/218#discussion_r492054749)

Ah yes. Even better. Let's do that to the microarray analysis notebook than too. Will change the title of this issue.
