### ISSUE TITLE
The PR Checklist is long; what can we automate reliably?

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#228]
There's a lot of items in the checklist for our human brains to do and remember. This takes a toll on authors of new examples and reviewers can miss some of these items over the iterative process of the PR reviewing. 

Now that we have some basic GitHub actions set up, we should see what checklist items the computers can take over for us. 

This will probably involve some edits to: https://github.com/AlexsLemonade/refinebio-examples/blob/master/.github/workflows/blank.yml

Beyond that I am unsure what this will involve at this point. Here is the PR checklist in its current state as well as some comments from me. 

Items that I don't think can really be automated because they are more content based: 
> *  All `{{BLANKS}}` have been replaced with the correct content.
> * [Sources are cited](https://github.com/AlexsLemonade/refinebio-examples/blob/master/CONTRIBUTING.md#citing-sources-in-text)
> * Seed is set (if applicable)
> * Comments and documentation are up to date. 
> * Removed any manual numbering of sections.
> * Removed any instances of chunk naming.
> * Added the `.html` [link to the navigation bar](https://github.com/AlexsLemonade/refinebio-examples/blob/master/CONTRIBUTING.md#add-new-analyses-to-the-navbar).

This could be more automated, but we'd need to figure out feedback:
> * Spell checked any Rmd file or md file. 
> * Check links

I don't think we want this automated because security on AWS would be sticky?
> * Added [data and metadata files to S3](https://github.com/AlexsLemonade/refinebio-examples/blob/master/CONTRIBUTING.md#adding-datasets-to-the-S3-bucket).

Probably the most prime suspects for automation: 
> * Any not yet added packages needed for this analysis have been added to the Dockerfile and it successfully builds.
> * In the Docker container, [snakemake was run for rendering](https://github.com/AlexsLemonade/refinebio-examples/blob/master/CONTRIBUTING.md#how-to-re-render-the-notebooks).

**Comment by jashapiro** [comment]
As we get into more an more modules, every addition requires a small change to every previous file (to keep the html up to date). This is a bit annoying for review, and it would be nice if we could separate the changed `html` files from the `Rmd` files. I think this should be possible with some automation; commits to master could be set to rerender the full site, and we could change the contribution guidelines to suggest not committing html files (or even add them to the ignore list)?

This comment is partly born of clicking past a bunch of html files with changed headers...

**Comment by jashapiro** [comment]
Thinking about this just a bit more... Maybe we could have a staging branch? It might be nice to be able to separate the pull requests for new modules into "infrastructure" and "content" PRs that would go into a "staging" branch. The first PR would have the intro material and changes to headers, etc and could be quickly reviewed. The second PR would include new content that might take a bit more discussion, but could be a smaller (and so less burdensome to wade through logistically) PR than the current multi-file PRs.

**Comment by jaclyn-taroni** [comment]
Going to attempt to synthesize the last two comments and state them in a slightly different way to see if we're on the same page and also add some more details that I think could be helpful for discussion. I think we're basically considering a simplified version of the [Gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) that's less focused on _releases/release branches_.

For this purpose, I am going to assume that when you say _module_, you mean smallest unit of new content that should be in the branch that GitHub Pages is built from (`master` at the moment but if we're overhauling this anyway, seems like a time to make a change). But if we are to write up guidelines, we should hammer out what that smallest unit is (born out of confusion on #223).

**Okay, this would go:**

- We create a `staging` (or `develop`) branch from `master`.
- Feature branches are created from `staging`, where a feature branch contains all the relevant changes for a **pull request** to `staging`. 
  - For each module, there will be _at least two_ feature branches and therefore pull requests. For example, let's consider a simple example where I am developing a module that will be comprised of a _single notebook_.
    - The first pull request could come from `jaclyn-taroni/infrastructure/cool-notebook`, which stubs in the notebook using the Rmd template and also includes changes to the navbar, etc. (Again, we should hammer out what exactly goes into an infrastructure PR and if it fits neatly within our current model or if tweaks are required.) 
    - The second pull request could be filed from `jaclyn-taroni/content/cool-notebook` and would contain the module-specific changes that make that notebook different from the template. That PR's discussion would ideally be focused on content.
- Once all feature branches for a module are merged into `staging`, we create a pull request to merge into `master`.
- I think we might also want to keep the notion of a `hotfix` branch from Gitflow (e.g., I found a broken link in `master` and want to quickly fix it).

An opportunity for automation could be the commit to `master` from `staging` or a `hotfix` branch, upon which :all_the_things: are rerendered.

**Comment by jashapiro** [comment]
This is kind of what I was thinking, but on reflection, I think we can simplify by flipping the order. 

- PR1: all the changes that are part of the new document and its requirements, with the exception of changes to `navbar.html` This will prevent most of the extraneous changes in other pages, and simplify review.

- PR2: Change `navbar.html` to add links everywhere to the new page.

This has the advantage of allowing a live look at the rendered files before it is linked into navigation, and no major changes to the development cycle.

**Comment by jaclyn-taroni** [comment]
Do you think changing the order eliminates the need for a `staging` branch? I do.

**Comment by jashapiro** [comment]
Yes, that is what I meant by no major changes to development cycle.

**Comment by jashapiro** [comment]
Pulling from discussion here to this more appropriate issue: https://github.com/AlexsLemonade/refinebio-examples/pull/238#issuecomment-699631239

I don't know if we want one meta-action for building the docker image and the website, but I think that might actually make sense. If we add to the `build-push:` job in #238, I think we can just use that image in a following `step` that performs the snakemake call described in [`CONTRIBUTING.md`](https://github.com/AlexsLemonade/refinebio-examples/blob/7b90e967f96ed6846cb77c40bcdeb48bb3fc13ea/CONTRIBUTING.md#run-snakemake-without-queueing-up-a-web-browser-for-the-docker-container)

Github actions can also be triggered by only modifications to particular files. This may well be useful so that we can have an action that pushes updated `.html` files to master without retriggering an endless loop of rebuilds. See https://github.com/r-lib/actions/blob/master/examples/render-readme.yaml for an example. (One thing I do not know is if you can restrict by `branch` and `path` and if those are treated as AND or OR)

**Comment by cansavvy** [comment]
I think this is largely wrapped up and the aspects that aren't wrapped up have their own more detailed issues.
