### ISSUE TITLE
Automation: run `styler` with GitHub Actions

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#231]
Related to #228 and the closed issue #154 that went a bit off track...

`styler` is run as part of the Snakemake workflow: https://github.com/AlexsLemonade/refinebio-examples/blob/40aa22a415ec5a92c3f31fc92965822ab4d03b4f/Snakefile#L17 and https://github.com/AlexsLemonade/refinebio-examples/blob/40aa22a415ec5a92c3f31fc92965822ab4d03b4f/scripts/render-notebooks.R#L85

You might think makes adding `styler` to GitHub Actions redundant and I would not disagree with you! _However_, in our quest for not making human pull request reviewers (and authors) do things that computers can do for us, it would be useful to break that ultimate goal into tasks that are relatively small in scope so we can get started.

I believe running `styler` in GitHub Actions would require us to do the following:

1. Install `styler`
2. Run `styler` on :all_the_things:
3. Commit the styled results and push

Here's an example I found: https://github.com/r-lib/actions/tree/master/examples#when-it-can-they-be-used

**Comment by jashapiro** [comment]
I will be curious how this works without triggering itself if it set to run on pushes or pull requests. It looks like the example in https://github.com/r-lib/actions/tree/master/examples#when-it-can-they-be-used is triggered based off a comment with the keyword `/style`, so that trigger seems external.

**Comment by jashapiro** [comment]
Never mind, github has smart people: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token

**Comment by jashapiro** [comment]
Right now, the docker build action is run on every PR commit, this isn't too slow, but it isn't fast. We can replace that with a `styler` action to run on every commit, and modify the docker build action (see [example](https://github.com/AlexsLemonade/refinebio-examples/blob/c6035c2a15e5be2bacc1b26e9ef0a722b8d8dfdf/.github/workflows/docker-build-push.yml#L8))  to only run when there are changes to Dockerfile.

**Comment by cansavvy** [comment]
I can take a whack at this.

**Comment by cansavvy** [comment]
Since styler is already installed on the docker image, should we skip: 
> 1. Install styler

And instead run on the docker container?

**Comment by jashapiro** [comment]
Yes, run in the docker container. Doesn't need to be the one that is part of the commit even.

**Comment by cansavvy** [comment]
> Doesn't need to be the one that is part of the commit even.

What? Also is there a reason to do it this way and also how?

**Comment by jashapiro** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer

I *think* if you include
```
container: ccdl/refinebio-examples:latest
```
it will pull and use that container.

Pulling should be faster than building every time is the only reason, and styler will not depend on added things.

**Comment by jashapiro** [comment]
If styler is installed with the base rocker image, you could even just use that for even more 🐎
