### ISSUE TITLE
[Idea] Make a url redirect that's easier for users to remember

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#234]
It's very difficult to remember the github pages url for the refinebio-examples pages. I imagine that the refinebio-examples will be a thing that users may look at and come back to but they will be less likely to return if there's not an easier url to use/remember. 

Can we make a shorter url that redirects to the main refinebio-examples getting started page? I know how to do it if we want it to be off of `ccdatalab.org` like `ccdatalab.org/refinebio-examples` but it might make more sense to have it off of `https://www.refine.bio/` like `https://www.refine.bio/examples`. But, I don't know where/how to do that for refinebio.org.

**Comment by jaclyn-taroni** [comment]
What about a subdomain like `examples.refine.bio`, which would mirror how we link to the docs? This seems like a _frontend_ ticket to me but I'll ask.

**Comment by cansavvy** [comment]
Something that is shorter than https://alexslemonade.github.io/refinebio-examples/01-getting-started/getting-started.html is good.

**Comment by jaclyn-taroni** [comment]
@dvenprasad - this is the issue we discussed!

**Comment by dvenprasad** [comment]
`examples.refine.bio` sounds good to me.

**Comment by jaclyn-taroni** [comment]
Filed https://github.com/AlexsLemonade/refinebio/issues/2542 to track this change. Closing this issue.
