### ISSUE TITLE
Automation: Build Docker image and push to Dockerhub upon merge

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#236]
Related to #228 

[Our contributing guidelines](https://github.com/AlexsLemonade/refinebio-examples/blob/master/CONTRIBUTING.md#pushing-docker-image-updates) state:

> All necessary packages needed for running all analyses should be added to the Dockerfile and it should be re-built to make sure it builds successfully.
>
> ...
>
> After a PR with Dockerfile changes is merged, its associated image should be pushed to the Docker hub repository.

It would be great to automate:

1. Ensuring the Docker image can build upon filing a pull request.
2. Build the Docker image and push to Dockerhub (`ccdl/refinebio-examples:latest`) upon merge to `master`. 

Here are a few examples/links I found that could come in handy:

- [Starter workflow YAML](https://github.com/actions/starter-workflows/blob/dacfd0a22a5a696b74a41f0b49c98ff41ef88427/ci/docker-image.yml)
- [Example for pushing to Dockerhub](https://github.com/containrrr/watchtower/pull/438/files)
- [Build and push Docker images from Marketplace](https://github.com/marketplace/actions/build-and-push-docker-images)

First we should establish how long we expect this to take by building locally with `--no-cache`. We may need help setting up the secrets from the engineering team.

**Comment by jashapiro** [comment]
I think we can tackle this in two steps as outlined. We can do #1 without any secrets, so I think that is worth setting up on its own first.

I can take that step to start.

**Comment by jashapiro** [comment]
It seems like there is now the ability to leverage caches, but I have not explored this yet: https://github.com/docker/build-push-action#leverage-github-cache
