### ISSUE TITLE
Automation: Spell checking files

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#239]
Related to #228 - The PR checklist is long and it's hard to make sure that more than the _initial submission_ adheres to the checklist.

I'll note that I think this is lower priority than some other `automate all the things` items. My intention, in part, is to illustrate how processes are intended to help us and ultimately the folks that are going to use these examples.

### Context

One of the items in the pull request checklist is 

> Spell checked any Rmd file or md file.

Where [the instructions for how to run spell check](https://github.com/AlexsLemonade/refinebio-examples/blob/7b90e967f96ed6846cb77c40bcdeb48bb3fc13ea/CONTRIBUTING.md#how-to-spell-check) are

> In R, run the following:
> ```
> dictionary <- readLines(file.path("components", "dictionary.txt"))
> spelling::spell_check_files("<tech-section>_<file_name>.Rmd",
>                             ignore = dictionary)
> ```
> Any terms that should be recognized by the spell check, you can add to `components/dictionary.txt`.

The purpose of using a spell checking mechanism is, in part, to help us enforce [formatting of typical words/items](https://github.com/AlexsLemonade/refinebio-examples/blob/7b90e967f96ed6846cb77c40bcdeb48bb3fc13ea/CONTRIBUTING.md#formatting-of-typical-wordsitems). Here's a selection of the items listed there: 

>   - Use "refine.bio", NOT "refinebio"
>   - Use `.Rmd`,  NOT "Rmd" or ".Rmd"
>   - Use "tidyverse", NOT "Tidyverse"
>   - Use "TSV",  NOT tsv or `tsv` or .tsv
>   - Use "PNG", NOT png or `png` or .png (and etc.)

A large reason **why** we have those guidelines has to do with the _intended audience_ for these examples. Using these terms/formatting inconsistently can be unnecessarily confusing for someone being introduced to them for the first time.

### Problem

To understand how we might automate spell checking, I followed the spell check instructions for a number of Rmd files for the microarray examples. There were a number of misspellings according to `spelling::spell_check_files()`. As a result, I had some observations.

1.  "Rmd" was flagged as a misspelling consistently at the _beginning_ of notebooks. "`.Rmd`" is included in the custom dictionary, but "Rmd" is not: https://github.com/AlexsLemonade/refinebio-examples/blob/7b90e967f96ed6846cb77c40bcdeb48bb3fc13ea/components/dictionary.txt#L8

Because the error was consistently at the beginning of the notebooks, it came to my attention that the _template_ was not following our guidelines - it has "Rmd" not "`.Rmd`": https://github.com/AlexsLemonade/refinebio-examples/blob/7b90e967f96ed6846cb77c40bcdeb48bb3fc13ea/template/template_example.Rmd#L114

This is something we should fix and using `spelling::spell_check_files()` allowed me to find it.

2. The custom dictionary `components/dictionary.txt` hasn't been updated since August 19 ([file](https://github.com/AlexsLemonade/refinebio-examples/blob/7b90e967f96ed6846cb77c40bcdeb48bb3fc13ea/components/dictionary.txt)). As a result, I expect folks get a number of "misspellings" that are not cause for concern (e.g., "zebrafish") if they run this according to the instructions and checklist. That makes things like what I raised above harder to detect and fix.

**Although the current process was an improvement over the built-in RStudio methods (#188), these items suggest to me that the way in which spell check is run currently could be improved.**

### Idea

To solve the problem, we would want to automate running spell check in two different cases that can most likely be addressed with the same workflow:

1. Initial filing of a pull request
2. When new updates (commits) are pushed to the pull request branch

We probably only want to check R Markdown and Markdown files that are altered in a pull request.

Here's what `spelling::spell_check_files()` returns when there are spelling "errors"

```
  WORD              FOUND IN
️               dimension-reduction_microarray_01_pca.Rmd:16
Brems             dimension-reduction_microarray_01_pca.Rmd:329
histological      dimension-reduction_microarray_01_pca.Rmd:287,308
medulloblastoma   dimension-reduction_microarray_01_pca.Rmd:83,85,200,266
molecularly       dimension-reduction_microarray_01_pca.Rmd:266
Rmd               dimension-reduction_microarray_01_pca.Rmd:110
softwares         dimension-reduction_microarray_01_pca.Rmd:336
subtype           dimension-reduction_microarray_01_pca.Rmd:287,308
```

And if I temporarily add all those words to `components/dictionary.txt` and rerun

```
  WORD  FOUND IN
️ dimension-reduction_microarray_01_pca.Rmd:16
```

This is always going to happen because of 

```
⬇️ [**Jump to the analysis code**](#analysis) ⬇️
```

My **general idea** is that we want to count how many "lines" are in what `spelling::spell_check_files()` as the _check_ (i.e., if there are more than two, this should fail) and post the output as a comment on the pull request ([artifacts documentation](https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts)). This general idea is similar to what happens on the OpenPBTA-manuscript repository with AppVeyor.

Someone would need to look into the specifics to determine feasibility. 

This would require us to keep `components/dictionary.txt` up to date, which we probably want to do in the interim anyway.

**Comment by cansavvy** [comment]
This seems like a good plan to me and yes, `dictionary.txt` has been neglected. The spell check plan I tried to put into place I was never very sold on #188 and I don't think with all the other items on the checklist, we've been very good at keeping up with it.

**Comment by cansavvy** [comment]
I'm going to start working on making or spell check automatic with Github actions, realizing that this will like bring up a lot of spell check errors, so I think the steps might be in two PRs: 

PR1: set up spell check in github actions as a part of the `styler.yml` (will probably rename?). But set up spell check errors minimum parameter as higher than it will be for real, so we don't also have to tackle spelling errors at this time. 

PR2: Address whatever spelling errors come up in all the files and update dictionary.txt as needed.

**Comment by jashapiro** [comment]
I think we may want this in a separate action, as commits from `styler.yml` will not trigger rerunning of the spellcheck step when we require it as a condition of merging. It may work fine, so I think it is fine to start as a separate job within `styler.yml`, but we shall see.
