### ISSUE TITLE
Style add/update: `IDs` NOT `ids` or `Ids` 

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#243]
In the most recent `gene-id-annotation` examples @cbethell, she went with `IDs` for the standard style (which we did not have addressed in the style guide at the time). 

We need to update the CONTRIBUTING.md and search and replace all the instances where `id` or `Id` or any other, now obsolete style of this is being used, most importantly any instances in the template. And then we need to re-render everything of course.

**Comment by jaclyn-taroni** [comment]
We should probably consider pushing all items like this to a stage of the project where we're polishing things and use a label to help us do that.
