### ISSUE TITLE
Change to the PR process and to CONTRIBUTING.md

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#245]
When new examples are added to `_navbar.html` all examples are rerendered and clutter up the PR with the changes. 

From the discussion on #228: https://github.com/AlexsLemonade/refinebio-examples/issues/228#issuecomment-699561760
The plan is to split up example add PRs into 2 PRs (both to master). 

> * PR1: all the changes that are part of the new document and its requirements, with the exception of changes to `_navbar.html` This will prevent most of the extraneous changes in other pages, and simplify review.
> * PR2: Change `_navbar.html` to add links everywhere to the new page.
> 
> This has the advantage of allowing a live look at the rendered files before it is linked into navigation, and no major changes to the development cycle.

This new plan needs to be described in more detail in CONTRIBUTING.md and we can hash out some specifics on this issue.

**Comment by cansavvy** [comment]
Now that the automation pieces are mostly (not quite all) merged, this would be a good thing to test out: see how it works and looks from the author side as well as reviewer side.

**Comment by jashapiro** [comment]
In light of #256 and https://github.com/AlexsLemonade/refinebio-examples/pull/254#issuecomment-701372041, I have some new thoughts and ideas. 

If we remove `_navbar.html` from the `input:` directive for rendering a page, pages will only rerender by default if the underlying `.Rmd` file is changed. This was not the behavior we would want when triggering renders manually, as we wanted changes to the navbar to force changes to all pages, so people would not forget.

However, in #254 we will force all pages to rebuild on merge to master, which will incorporate any changes to `_navbar.html` regardless of whether `_navbar.html` is included as an `input` in each individual step. In other words, if we keep the `_navbar.html` changes in a PR associated with adding a page (and all content for that page), we will be able to preview it in the added page as part of the PR review, but merging that PR will result in rerendering of all pages, propagating that change to all "old" pages.

So what I am saying is that we can leave the instructions mostly as they are, with a single PR per page addition, but change `Snakefile` to accomplish the same overall goal of simplifying review to focus on the new content.

**Comment by cansavvy** [comment]
Chatting with @jashapiro on Slack, we discussed that with these updated changes to how PRs should go, we should also recommend that only the files that you are changing be committed and pushed in your PR. This way the session_info fluctuations we see in the files diff part of PRs are out of the way, and ultimately the automated snakemake step will make sure everything is up to date.

**Comment by cansavvy** [comment]
I _think_ any changes n PR strategies will be highly influenced by what's happening on #262

**Comment by cansavvy** [comment]
Now that gh-pages mechanics are working, I'm using little changes to test some things (#268). The `only push the Rmd and htmls you have focused on for this PR`, mentioned above, still stands, because now github actions will do a final rendering before merging.

**Comment by cansavvy** [comment]
Now that #274 is merged, this can be closed.
