### ISSUE TITLE
Changes when autorendering

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/refinebio-examples#256]
I just enabled pushing html files back to the repository after rendering in #254 , and I noticed a few things in the first pushed diff: https://github.com/AlexsLemonade/refinebio-examples/commit/e8169fc36de1e23434c19db2599a260baa42a2d7

The first is that, even though it is not October as I write this, it is for github actions robot.  So I am probably the first to see all of the files' date headers flip over from September to October. Because any changes to one page will lead us to rerender all of them, and our current `.Rmd` files in this repo have a dynamically-generated date in the header, this means that anychanges pushed to one file will cause all files to get that file's date in the header.  I would suggest that we go back to manual dates at the top of the page, so we don't see those changes all the time.

It might be worth putting the rendering date in the `Session Info` block to separate the rendering date from the writing date but keep a record of both. This should not affect local development too much, as most html files should not be rerendered often in that context (see #245), but that remains something to keep in mind, as it could result in more inconsequential changes.

The second set of differences are mostly changes in the order of dependencies (versions are unchanged), which mostly seems due to the absence of `rstudioapi_0.11`. I suspect this is the difference between rendering from within `RStudio` and directly from the docker image.

Interestingly, there are also a few of places where there are _slight_ changes in results: 
- In 02-microarray/dimension-reduction_microarray_01_pca.html, `PC285` has somewhat different values. This seems completely inconsequential (Why are we printing all 285 PC values for each sample? that is a LOT for people to scroll past.)
- In 03-rnaseq/differential-expression_rnaseq_01.html, a few values are slightly different. While in the previous example I could see no change in included packages, here there is a slight version change in `matrixStats`: 0.56.0->0.57.0
- A number of figures have changed (I have not looked at them in detail), but they should be compared; differences there are likely to be insignificant.

**Comment by cansavvy** [comment]
> rendering date in the Session Info block to separate the rendering date from the writing date but keep a record of both.

Would this be hard-coded thing? I will add it to the upcoming PR I'm working on. 

> In 02-microarray/dimension-reduction_microarray_01_pca.html, PC285 has somewhat different values. This seems completely inconsequential (Why are we printing all 285 PC values for each sample? that is a LOT for people to scroll past.)

I'm not sure I have too many leads for this, I've ran it myself and took a looked at e8169fc and I haven't been able to find any package changes that directly explain this. And I find it odd that its only the 285th PC? And RNA-seq PCA is unaffected? But, I do want to reduce all that print out, so I'll file something that just shows the first 10 columns. 

> A number of figures have changed (I have not looked at them in detail), but they should be compared; differences there are likely to be insignificant.

I suspect these are default dimension changes which we saw in OpenPBTA when there were docker fluctuations as well. But I need to look into it more. (Trying to find the most straightforward way to do that. 

> In 03-rnaseq/differential-expression_rnaseq_01.html, a few values are slightly different. While in the previous example I could see no change in included packages, here there is a slight version change in matrixStats: 0.56.0->0.57.0

I'm think? that this should stabilize after 10-10-20 when 4.0.3 drops? Does this seem correct/likely?

**Comment by jashapiro** [comment]
> Would this be hard-coded thing? I will add it to the upcoming PR I'm working on.

I'm not sure what you mean by hard-coded. I would say the date field should remove `r format(Sys.time(), '%B %Y')` and replace it with a placeholder for people to fill in and update manually.

Then if we switch to `sessioninfo::session_info()` we get the date for free! (Should come with tidyverse)

> And I find it odd that its only the 285th PC? And RNA-seq PCA is unaffected?

The last one probably because it is the smallest. It is probably a floating point error, but I am not worried about it.

**Comment by jashapiro** [comment]
I think all the plots that are changing are jitter plots, which makes sense (if you think about it). We will want to add `set.seed()` to the following files to stop these changes:
```
02-microarray/differential-expression_microarray_01_2-groups.rmd
02-microarray/differential-expression_microarray_02_several-groups.rmd
03-rnaseq/differential-expression_rnaseq_01.rmd
```

**Comment by cansavvy** [comment]
> I think all the plots that are changing are jitter plots, which makes sense (if you think about it). We will want to add `set.seed()` to the following files to stop these changes:
> 
> ```
> 
> 02-microarray/differential-expression_microarray_01_2-groups.rmd
> 
> 02-microarray/differential-expression_microarray_02_several-groups.rmd
> 
> 03-rnaseq/differential-expression_rnaseq_01.rmd
> 
> ```

Oh of course!! I should have thought about that.
