### ISSUE TITLE
Automating pushes to master is not so easy

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/refinebio-examples#262]
In #254, #259 and #260, I tried to automatically build all of the html files on pushes to `master`, with the idea that we would rerender all the pages then and then push any changes back to `master` to keep everything neatly up to date. This did not go as well as I might have hoped. 

Because `master` is protected, we can't just let the github action push changes normally. I thought maybe we could force push the changes to get around the status checks, but that did not work, because the github actions "user" does not have permissions to push to that branch. I don't think there is any way to grant those permissions to the github actions user. 

The general solution to this is to use a "personal access token" (PAT) instead of the one associated with github actions,  where that PAT is associated with a user that _does) have permission to push (or force push) to the protected branch. This has consequences though. One of the neat things about using the default github actions token is that doing so means that it's actions can't trigger a new workflow. This prevents workflows from triggering themselves, which would be a bad thing in general. 

I do have some ideas for solutions though!

First, we could use a PAT with the existing workflow (see [checkout action docs](https://github.com/actions/checkout)), but restrict the workflow to run only when there are changes to a `Rmd` file, `_navbar.html`, or the bibliography. In other words, changes to rendered html files would not trigger the workflow. Since the workflow now only commits changes to html files, this should prevent infinite loops.

Second, we could move the rendered html files to live in a separate branch (e.g. `pages`), and then have github pages use that branch for rendering. Then changes to `master` would trigger an action that commits the changed html files to the `pages` branch. This branch would have a different set of restrictions, but I am not totally sure what they would look like. It probably makes sense to have this branch also protected, but with just a user restriction rather than the status check restrictions that we have. In other words, I think we would want to use a PAT here as well.

I think I had a third idea, but I forgot it while writing.

As far as setting up the token to use, we would need to do that with either one of our user accounts or with one of the Alex's bot accounts, and then store the token in the repository secrets. General instructions are here: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

Thoughts on these options, or ones I have not thought of?

**Comment by cansavvy** [comment]
> Second, we could move the rendered html files to live in a separate branch (e.g. pages), and then have github pages use that branch for rendering. Then changes to master would trigger an action that commits the changed html files to the pages branch. 

I kind of like the idea of keeping these things in separate branches. That _sounds_ like it would be cleaner?

**Comment by jaclyn-taroni** [comment]
> It probably makes sense to have [`pages`] also protected, but with just a user restriction rather than the status check restrictions that we have.

This looks relatively straightforward to set up based on [this documentation](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-branch-restrictions).

**Comment by jashapiro** [comment]
Yes, it should be fine. I wish there were an easy way to set the "github actions" user, but I can't find that. So we will probably want to use some bot user? Do we get a token for one the dev team has already made or make a new one?

**Comment by jashapiro** [comment]
Okay, I am going set up a `gh-pages` branch and start to make adjustments to push rendered pages to that branch.

**Comment by jashapiro** [comment]
I am not quite closing this, but #266 and previous commits has done most of the hard work. The only thing that remains is to change the source for the github pages to the `gh-pages` branch and update documentation. I have not done the former yet because I want to see how things go for a couple pushes first.

**Comment by cansavvy** [comment]
Based on how `gh-pages` is working, is it correct to say that we only want to commit and push htmls and Rmds that are pertinent to the PR at hand (and the rest will get re-run before merging anyway?)

**Comment by jashapiro** [comment]
I think that is correct (and any other files required). But I think it is okay if the html files in master are semi-out-of-date, as in not the most recent render (content should be the same, as the Rmd will be the same).

**Comment by jashapiro** [comment]
I have now switched the source branch for the website to `gh-pages` and with #274 in I think this can be closed!
