### ISSUE TITLE
Evaluate a single example: introductory material, set up, and navigation

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#263]
#### Purpose & idea

The purpose of this ticket is to track getting @dvenprasad's impressions for the following questions from https://github.com/AlexsLemonade/refinebio-examples/issues/145#issuecomment-692926901

> - Do users feel that the getting started information in each module provides all the information needed to complete the analysis? How do they feel about the flow and ease of following the steps?
> - How easily can users navigate between modules to find the information they are looking for?

To expand on these points a bit:

- There are 3 sections at the beginning of every example where the content varies very little: `Purpose of this analysis`, `How to run this example` and `Using a different refine.bio dataset with this analysis?` that are generally for following along locally having downloaded the `.Rmd` file.
	- What issues for the workflow for obtaining the `.Rmd` file and getting set up with a refine.bio dataset need to be addressed at this point?
	- It seems useful to consider how to best convey our message with images in the `How to run this example` at the same time (#199).

- You can also imagine a situation where someone is browsing the GitHub pages because they want to look only at the analysis part of the code. We have ⬇️ **Jump to the analysis code** ⬇️ in the `Purpose of this analysis` section to allow folks to do just that. Is there a better way to do this? (Feasibility is another thing, of course :smile:) 

- Is the navigation bar sufficient for navigating between modules?

#### Next steps

To me, the starting point is to look at a single example that is currently live on GitHub pages: https://alexslemonade.github.io/refinebio-examples/02-microarray/clustering_microarray_01_heatmap.html and file some 🎟️ !

**Comment by dvenprasad** [comment]
>Do users feel that the getting started information in each module provides all the information needed to complete the analysis? How do they feel about the flow and ease of following the steps?

Yes there is sufficient information to get started/ follow-along. It was relatively easy to start setting up. Getting the .Rmd files/dealing with Github was the biggest pain-point which has been eliminated 🎉  I had a couple thoughts on smoothing out the flow but nothing major. I have filed the issues 🎟️  :  #269 #270 

>How easily can users navigate between modules to find the information they are looking for?
Navigation is reasonable and easy to get around. 

- ⬇️ Jump to the analysis code ⬇️  worked well enough. I wouldn't change it. 

>What issues for the workflow for obtaining the .Rmd file and getting set up with a refine.bio dataset need to be addressed at this point?
For this specifically, my only comment is: can we use a screenshot without the error message? (🎟️  : #271)

**Comment by jaclyn-taroni** [comment]
Thanks for filing those @dvenprasad  ✍️ 🎟️ 🎉 ❗ I'm going to close this issue.
