### ISSUE TITLE
Replace download now modal image

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-examples#271]
![Screen Shot 2020-10-06 at 8 22 57 AM](https://user-images.githubusercontent.com/15315514/95201085-6a5abc00-07ad-11eb-9b62-67e2527f65ec.png)

Can we use one without the error message?

**Comment by cansavvy** [comment]
It automatically did that because it put my email in automatically and had to delete it, but I've taken a new screenshot that doesn't have that.

**Comment by cansavvy** [comment]
<img width="580" alt="download-email" src="https://user-images.githubusercontent.com/23458084/95392355-9ae24900-08c6-11eb-9213-123928a213dd.png">
 Here's an updated version of this image. 

Next step is search and replacing in the project all the image links. This can be done at the same time as #199
