### ISSUE TITLE
refinebio-examples feedback survey 

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#277]
As users are going through refinebio-examples we want them to be able to provide feedback. Our main points we want to know from them are: 
- Did they encounter any problems?
- Did they have the resources they need to get started?
- Did they find what the expected to find?

We can have a HubSpot survey linked in the navbar as well as at the end of each example. 

Here's a rough draft for what questions should be included: 

```
- What example analyses were you following today? (Presented as a checkbox list of the examples?)
- How useful did you find this example analysis? (a Likert 5 point scale of usefulness that pops up for each example they said they used)
- Did you encounter any problems? (See if there's a way for them to attach a screenshot). 
- What additional information would you have liked to seen? (Free text)
- How useful did you find the links and sources? (Likert 5 point scale)
- What other analyses would you like to see? (A multiple choice for new materials with Other as an option)
- What were you expecting to see on refinebio-examples that is not there? (free text)
- Provide your email if we can reach out to you for follow up questions in a 15 - 30 minute follow up interview. (email)
```

**Comment by cansavvy** [comment]
Here's a rough draft: https://share.hsforms.com/1pQ8pPB70TuG37sVjr-KtXA336z0

**Comment by cansavvy** [comment]
@dvenprasad I have a comment and two questions: 
Question 1: When people sign up for the emailing list on refine.bio, what HubSpot contact list does that correspond to? I made a guess on this workflow: https://app.hubspot.com/workflows/5187852/platform/flow/40104722/edit
Question 2: What refine.bio logo should be included on the form? (And should we remove one of the two that are on there now?)
Comment is, feel free to take a look at (and make edits to) the form whene you have time (the URL will not change so we can begin adding it to the examples in the meanwhile) https://app.hubspot.com/forms/5187852/editor/a50f293c-1ef4-4ee1-b7ee-c563afe2ad5c/edit/form

**Comment by cansavvy** [comment]
Something we will have to keep in mind and make procedures about is that the `Which examples were you following` question will need to be updated as we update modules (or change the name of them).

**Comment by cansavvy** [comment]
What should this feedback button say? @dvenprasad ?
- `Give us feedback` 
- `Feedback` 
- `Tell us how it's going` 
- `Survey`

I don't love any of these.

**Comment by dvenprasad** [comment]
I went with `Give Feedback`.

**Comment by cansavvy** [comment]
This is resolved except for figuring out how we want to keep question one: "Which examples did you use" up to date. I've tracked this on #332
