### ISSUE TITLE
Visual Unity: Make _navbar.html more match-y with refine.bio

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#278]
To make it less looking like users have jumped to a different site when they go to refinebio-examples, we should try to spruce up the navbar to make it match the refine. bio color schemes and maybe have the refine.bio logo. 

Recall that only the [main `_navbar.html`](https://github.com/AlexsLemonade/refinebio-examples/blob/master/components/_navbar.html) needs to be changed and this should propagate to all the examples.

Here are all the refine.bio design items we will need to do this:
https://github.com/AlexsLemonade/refinebio-design

I don't know anything about CSS, but @dvenprasad said we should be able to add a bit to the _navbar.html to make it match-y.

**Comment by dvenprasad** [comment]
Here's the styleguide https://github.com/AlexsLemonade/refinebio-design/blob/master/styleguide-dev.pdf

**Comment by cansavvy** [comment]
We should be able to borrow the things I figured out with David's help on #282 for this too.

**Comment by cansavvy** [comment]
I think this is all set, except for what's now tracked on #323
