### ISSUE TITLE
[Idea/Question] Tag a new release of refinebio-examples before "going live"

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#285]
Do we always want to keep refinebioi-examples as releases and tags? This would be nice as far as making new material releases more intentional, but would also mean more hassle to bug the dev team to update the links (I think). 

Not sure what makes most sense.

**Comment by jashapiro** [comment]
We may be able to use a `current` tag and move it as necessary? https://stackoverflow.com/questions/8044583/how-can-i-move-a-tag-on-a-git-branch-to-a-different-commit

**Comment by jaclyn-taroni** [comment]
I wanted to get this back on our radar. It would be great to have this implemented before next sprint starts in interest of smoothing the way for any development on the frontend that might happen next sprint.

**Comment by cansavvy** [comment]
Here's a release draft: https://github.com/AlexsLemonade/refinebio-examples/releases/tag/untagged-5b2b283cd6af509a3245 I'm not sure if there's more pertinent info that should be put in the release? Perhaps we want to name it something else?

**Comment by jaclyn-taroni** [comment]
Would you plan be to move the `v2.0` tag and that's what the front end would point to? Or should we use `current` like @jashapiro suggested here https://github.com/AlexsLemonade/refinebio-examples/issues/285#issuecomment-706182163 and a strategy where we have a release every time we merge to `master`? I think I'm going to ask in Slack about the second point (do we need to release often).

**Comment by cansavvy** [comment]
I *think* using `current` makes sense?

**Comment by jaclyn-taroni** [comment]
Closing this. New issues coming soon based off of discussion in Slack.
