### ISSUE TITLE
refinebio-examples: Going Live!

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#286]
In this instance, `going live` means we've relinked the current refinebio-examples to refine.bio (Currently its linked to v1 of this repo). 

This is an epic since there a list of issues we need to get done before going live. 

A future set of issues that will be added to this epic but are not known yet, is what information the usability evals bring up #145 

Before going live we will need to figure outa mostly complete doable plan for #297 

These items should be on this Epic but are on other repos. 
https://github.com/AlexsLemonade/refinebio/issues/2542 - Shorten the URL
https://github.com/AlexsLemonade/refinebio-frontend/issues/926 - restructuring examples on home page

**Comment by jaclyn-taroni** [comment]
🎉
