### ISSUE TITLE
Add syntax highlighting to code

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/refinebio-examples#287]
Our currently rendered html files do not have syntax highlighting for R code, which makes me sad.

Can we implement something like https://highlightjs.org to automatically highlight our code?

https://highlightjs.org/usage/

**Comment by cansavvy** [comment]
I think an easier implement is https://bookdown.org/yihui/rmarkdown/html-document.html#appearance-and-style the `highlight` argument. I think `haddock` theme seems fine.

**Comment by cansavvy** [comment]
haddock looks like this: 

<img width="373" alt="Screen Shot 2020-10-19 at 3 17 08 PM" src="https://user-images.githubusercontent.com/23458084/96501298-31473080-121e-11eb-98b2-b1f6855d7385.png">
