### ISSUE TITLE
Editing: Pass through for content

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#290]
When reviewing examples one by one, it can be hard to keep an eye on the big picture. Specifically - keep an eye on things like the audience and assumptions about what that audience will know or is interested in. Once all the before going live examples go in, we should have at least one person go through the product as a whole and make notes about changes that should be made.

**Comment by cansavvy** [comment]
From a conversation I had with @jaclyn-taroni, just wanted to mention that this issue should ideally be completed by someone with "more distance" from this project. Someone who isn't as familiar with all the material. Aka not @cbethell or myself.

**Comment by jashapiro** [comment]
Closing this with the same logic as https://github.com/AlexsLemonade/refinebio-examples/issues/289#issuecomment-749110544. We'll catch any remaining changes with individual issues as they come up.
