### ISSUE TITLE
Further refine wording about: Why use microarray data?

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#296]
In the microarray section header, we have an "advantages of microarray" section. Currently we have a few listed bu tas @jashapiro noted here: https://github.com/AlexsLemonade/refinebio-examples/pull/232#discussion_r504189680 , our main point to our users about microarray is that it's useful, still relevant even thought RNA-seq exists, and it there's a lot of it out there that might prove to be helpful for their particular scientific questions and interests. 

I've struggled a bit with getting these points across eloquently in 02-microarray/00-intro-to-microarray.Rmd but I think this is something we should come back to because it's an important point to make.

**Comment by jashapiro** [comment]
Closed by #409
