### ISSUE TITLE
Restructure ORA example instruction -- more concise

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#306]
Related to this discussion: https://github.com/AlexsLemonade/refinebio-examples/pull/283#discussion_r505907273

The microarray ORA example needs some reorganization the instruction and steps used. 

Specifically, we should make it a bit more terse and specific but also look out for where we can highlight other decisions/methods that could be used. Should these other methods/decisions be their own example -- either an rna-seq example or a part of a set of ORA? OR can we just highlight with comments and further instruction how to alter the ORA example to fit one's needs; ultimately getting across that the decisions we made are somewhat arbitrary and are not an implicit rule (Josh's words).

**Comment by cansavvy** [comment]
Another more specific direction as a part of this issue is that some of the background information: see @jaclyn-taroni's  comment here: https://github.com/AlexsLemonade/refinebio-examples/pull/283/files#r506455366 can be moved to the pathway analysis introduction file (#214). 

Because this is the first pathway analysis module to be (re)added its conceivable that as we move along we will hammer out a strategy for this background information as well as what the "prescriptive but not a rule" instruction discussed here should look like.

**Comment by cansavvy** [comment]
This and the intro paragraph determined in #349 can be addressed at the same time.

**Comment by cansavvy** [comment]
An idea related to these changes from @envest: https://github.com/AlexsLemonade/refinebio-examples/pull/356#discussion_r527240743 Use a table. I think a lot of the info needs to be trimmed down here, but we can see if a table of sorts makes explanations more brief. (But we also might just be able to get rid of the explanations entirely and link out to somewhere that explains it well (a strategy we've used a lot when we are trying to be brief but still give info).

**Comment by cansavvy** [comment]
Found a nice source for explaining hypergeometric tests in context of genes: https://dputhier.github.io/ASG/practicals/go_statistics_td/go_statistics_td_2015.html

**Comment by jaclyn-taroni** [comment]
In my opinion, this was fully addressed by #377.
