### ISSUE TITLE
Fix/add refine.bio logo to navbar

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#323]
@dvenprasad did some work with the CSS file on #303  and navbar to get refinebio-examples to better resemble refine.bio (#278). 

The last thing left is the logo wasn't able to be incorporated without misbehaving: 

From @dvenprasad 's comment on #303: https://github.com/AlexsLemonade/refinebio-examples/pull/303#issuecomment-714516285

> The only thing I wasn't able to do was get the logo to sit properly in the navbar. It cut out. And when I tried to make the navbar accommodate it, it just overlapped with the content, instead of pushing it down. So for now I've replaced the logo with text until someone else can take a pass at it.
> 
> <img alt="Screen Shot 2020-10-22 at 9 25 05 AM" width="1202" src="https://user-images.githubusercontent.com/15315514/96882517-62597800-144d-11eb-84a0-bc119e3dfcfc.png">

This is something we can revisit later. Perhaps have someone from the dev team take a look at it.

**Comment by jashapiro** [comment]
I put some ideas for solution here: https://github.com/AlexsLemonade/refinebio-examples/pull/303#issuecomment-714528242

**Comment by jashapiro** [comment]
The comment above also notes that there is a rendering glitch when the menu gets small but not too small: 

![](https://user-images.githubusercontent.com/20483/96883000-e3187400-144d-11eb-9659-e5422c441405.png)

It would be good to solve that related problem with this one, if possible.
