### ISSUE TITLE
Make diagrams that explain the two-branch set up for PR processes

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#330]
### Background

#297 has made our PR process better, but also more complicated. #313 is adding a lot of information about our two-branch PR process in our CONTRIBUTING.md and it can be a lot to absorb and visualize in your head. 

@jaclyn-taroni had the idea of making illustrations that describe this process so we can save our brain energy for elsewhere but so we can still leave the CONTRIBUTING.md doc with the idea of how PRs on this repository should work. 

### Problem

There's a lot of different branch names, github actions, and steps for our PR process now that we are implementing #297 
We need a diagram to explain this so contributors don't have to spend a lot of time learning how this works. 

#### What items should be incorporated into the diagram? 

The diagram should explain/include
- The branches: staging, gh-pages-stages, master, gh-pages and what are they, what are their purposes, what do they matter to me? 
- What's do the github actions robots do in between each step? When are things being triggered? 
- What's happening with the Docker image at each step? 
- What do the two scenarios describe for staging changes - > master look like (specifically about the cherry commits). 
- How do master and staging relate throughout? 

### What are the recommended next steps?

- Let's take a look at other places on the web where they have these diagrams and they do it well for inspiration: 
     - https://www.atlassian.com/git/tutorials/comparing-workflows
     - https://nvie.com/posts/a-successful-git-branching-model/
- Post a rough sketch of what this should look like here. 
- Maybe make a prettier one using a graphic making app of some sort. Also post here. 
- Finally add the diagram to CONTIRBUTING.md

**Comment by cansavvy** [comment]
I tried coloring by hand but it was too tricky. https://docs.google.com/presentation/d/1rbaXRYos1aP7u2cik7z7KTLMzX_ogU99gxsGWk22-gM/edit#slide=id.ga4c13fdd75_0_117

![hotfix-pr](https://user-images.githubusercontent.com/23458084/97034866-8beccf00-1533-11eb-8288-a7360dbc5661.png)
![all-changes-pr](https://user-images.githubusercontent.com/23458084/97034868-8beccf00-1533-11eb-88d8-c49a694110a6.png)
![some-changes-pr](https://user-images.githubusercontent.com/23458084/97034870-8c856580-1533-11eb-9393-f646ca0d89e6.png)

**Comment by jashapiro** [comment]
Couple quick thoughts: In the first one, there should be one middle track that represents the *branch*, not the PRs. In my mind, the PRs and merges are the curvy arrows (branch *events* too, but let's leave those aside); I might differentiate those somehow. (Both are ultimately merges, but one has a review step). So the hotfix branch would come off of master, get merged back into master by a PR, then get a merge from Staging and then PR back to staging. Something like this:
![A2B1BE85-FC6D-419F-B28F-26DA4D0F1305_1_102_o](https://user-images.githubusercontent.com/20483/97035872-f9e5c600-1534-11eb-80d8-28e0c43ee750.jpeg)

**Comment by jaclyn-taroni** [comment]
I was typing on my phone to say the same thing but then decided sketching a picture would be better ☝️ !

**Comment by jashapiro** [comment]
- Try to make your curvy arrows always go downward? (think of the dots as being arranged in time, with the future down, so you can't take things back in time) 

- I think one thing that @jaclyn-taroni was looking for here was an explanation of when robots get triggered and what happens when they are. I think that may be best shown as separate from these exact diagrams: the details of finished and unfinished projects are not really important there, so you could show it with one "project" branch, staging, and master.

- What are the grey arrows?

**Comment by cansavvy** [comment]
I think this has incorporated these comments? Let me know how you guys feel about these changes. 
![some-changes-pr](https://user-images.githubusercontent.com/23458084/97168090-406a3900-175e-11eb-8599-b6accdb20bfa.png)
![all-changes-pr](https://user-images.githubusercontent.com/23458084/97168091-4102cf80-175e-11eb-8030-8427d3815fd1.png)
![hotfix-pr](https://user-images.githubusercontent.com/23458084/97168286-90e19680-175e-11eb-8781-e9b8bbf23e7f.png)

**Comment by jaclyn-taroni** [comment]
I do agree with @jashapiro that I don't think the robots part needs to be in the same diagram. (I think I brought this up in Slack as well.) As these stand, I find them to be a bit busy in a way that detracts from our goal.

Also consider: are all the details of what's going on with an finished vs. unfinished project getting merged on the left hand side necessary? If so, does it _need_ to be in the same diagram as the merge to staging or can that diagram be broken up into pieces?

More general comment for both @cansavvy and @jashapiro - why would we need to merge something from staging into a hotfix branch?

**Comment by cansavvy** [comment]
> More general comment for both @cansavvy and @jashapiro - why would we need to merge something from staging into a hotfix branch?

I think this is so the hotfix is added to the up to date version of staging and we don't accidentally save over changes when we use the master branch. 

I've split up gha into its own thing and tried to simplify the other diagrams. How is this? 
![gha-summary](https://user-images.githubusercontent.com/23458084/97172537-88408e80-1765-11eb-9a6f-b655dc0f6abc.png)

**Comment by jaclyn-taroni** [comment]
That makes sense re: hotfix, I suspect with the checks that's going to be a somewhat passive process.

**Comment by jaclyn-taroni** [comment]
That GHA diagram doesn't say when something runs. What is the action contingent upon?

**Comment by cansavvy** [comment]
> That GHA diagram doesn't say when something runs. What is the action contingent upon?

The first sentence at the top. I can make it is own column if that's better, thought that might make it more complicated than needed.

**Comment by cansavvy** [comment]
![gha-summary](https://user-images.githubusercontent.com/23458084/97173911-ad360100-1767-11eb-8d71-c62bde24f3fa.png)
