### ISSUE TITLE
The multiple pull request templates do not show up 

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/refinebio-examples#336]
### Background

We added the PR templates in #334 but now they aren't really showing up, this is not a shock, but I still want to make sure its track. 

### Problem

I tried following https://github.blog/2018-01-25-multiple-issue-and-pull-request-templates/  and not shockingly, it did not work as seemed to indicate it should (they made it sound like it was so simple but I don't think that it is THAT simple). 

### What are the recommended next steps?
I'm going to do more Dr. Google asking and digging into github docs, looking for examples of where someone might have gotten multiple PR templates to work.

**Comment by cansavvy** [comment]
Oh I see what that blog meant about the URLs, the templates can populate your PR if you add an ending with `expand=1&template=<TEMPLATE_FILENAME>` : https://github.com/AlexsLemonade/refinebio-examples/compare/cansavvy/survey?expand=1&template=hotfix-pr.md

**Comment by cansavvy** [comment]
When you open a PR, it is populated with the links to the templates and if you click on Preview you can click on the link directly and it will bring you to the template! :tada: I think this might be as good as we are going to get.

**Comment by jashapiro** [comment]
> When you open a PR, it is populated with the links to the templates and if you click on Preview you can click on the link directly and it will bring you to the template! :tada: I think this might be as good as we are going to get. 

Cool that this works! Thinking about the common workflows though... we might want to make the "standard" PR the default template, but include links to the hotfix and publish templates as part of the intro?

Saves some clicks (going to preview mode, especially) in the most common case.

**Comment by cansavvy** [comment]
> we might want to make the "standard" PR the default template, but include links to the hotfix and publish templates as part of the intro?

I think having the general `Other` PR template as the default makes sense and having links to the others makes sense.
