### ISSUE TITLE
Add introductory paragraphs to microarray GSEA example, review text for RNA-seq GSEA example

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/refinebio-examples#354]
### Background

Per [this related comment on PR #347](https://github.com/AlexsLemonade/refinebio-examples/pull/347#pullrequestreview-530420731), the microarray pathway analysis GSEA example notebook will need to be updated to reflect changes made to the introductory paragraph for the pathway analyses examples in once issue #349 is completed.

### Problem

Per issue #349 and [this comment on #340](https://github.com/AlexsLemonade/refinebio-examples/issues/340#issuecomment-723272256), the pathway analyses examples do not currently contain background information on how to choose a pathway analysis based on one's question and dataset.

### What potential "gotchas" do we know of?

Not aware of any potential "gotchas" at the moment.
However, additional context changes may need to be made throughout the notebook based on what is added in the introductory paragraphs.

### What are the recommended next steps?

Once #349 is completed, the introductory paragraph determined there would need to be copied over to the `02-microarray/pathway-analysis_microarray_03_gsea.Rmd` notebook, remembering to re-run the Snakefile in order to update the rendered html.

### Is there a particular timeframe for this issue?

 

Once #349 is addressed, this issue should take ~1/2 day to complete.

**Comment by jaclyn-taroni** [comment]
I noticed the following while taking a look at #397. We have a section header that talks about `clusterProfiler`'s options. That section is about `msigdbr`.

https://github.com/AlexsLemonade/refinebio-examples/blob/94649c66f04d167d65d06dfc4eca3fca4ee3671d/02-microarray/pathway-analysis_microarray_02_gsea.Rmd#L180

**Comment by jaclyn-taroni** [comment]
The issue with this header is also in the ORA example I spot checked, will file a new issue.

**Comment by jaclyn-taroni** [comment]
Closed via #434 and #437
