### ISSUE TITLE
Come up with a UE test plan to test the examples

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-examples#41]
Test users looking/using at examples.

Questions: 
- What are specific things we want to know from testing?
- What are we unsure about the way examples are currently presented?
- Which type of users should we target? 
- Which examples would be appropriate to test?

tagging @jaclyn-taroni and @cansav09 for input.

**Comment by dvenprasad** [comment]
> What are specific things we want to know from testing?
We want to know:
- Are users able to plug in their own data in the examples?
- Can they run the example as is locally?
- Are users able to easily transition to Gene Pattern?

> What are we unsure about the way examples are currently presented?
- How do we present GenePattern in way that is functional?
- Do people want more background information on analysis method?

>Which type of users should we target?
early-mid experience with bioinformatics 

>Which examples would be appropriate to test?
- Differential Expression
- ENSEMBL ID conversion
- One of Pathway analysis

**Comment by dvenprasad** [comment]
Based the goals and questions we want to answer, I came up with a high level set of scenarios and tasks for the user to do.

## Scenario 1: Explore Pathway Analysis
Most likely get redirected to the example repo via the landing page/the docs

**Tasks**
- Setup
- Run Notebook

**Questions this task should answer:**
- Was there enough information for users to successfully get setup?
- Did they succeed in getting setup?
- Were they able to run the notebook locally? 
- Did they receive sufficient information about the analysis method?

## Scenario 2: ENSEMBL ID Conversion
Get to the example either via next steps (if implemented) or docs

**Tasks:**
- Download data from refine.bio (Should we pick out a specific experiment or will it be okay for them to pick the experiment?) 
- Navigate to example and get required files.
- Explore and plug-in the dowloaded data into the experiment.

**Questions this task should answer:**
- Were they able to figure out where they should/can plug in their own data? 
- Could they make other code changes to accommodate their dataset? i.e metadata stuff (if applicable)  

## Scenario 3: Differential Expression
Get to the example either via next steps (if implemented) or docs

**Tasks:**
- Download data from refine.bio (Should they work with the same dataset from before? Should we pick out another specific dataset for them?) 
- Navigate to example
- Use GenePattern Notebook to do analysis. ( I'm only concerned whether or not they are able to generate the .gct file and load it into the GenePattern notebook. Whether or not they are able to complete the analysis on GenePattern is not in scope.) 

**Questions this task should answer:** 
- Were users given the tools and information to successfully use refine.bio data with GenePattern Notebooks?
- Could they generate .gct file?
- Was there enough information about the analysis method? 

@jaclyn-taroni @cansav09 Does this sound reasonable? 

The next step is write up a script for the test which will flesh out the scenarios, tasks, and the questions we ask users at each stage. 

I want to note that this test plan outline is ambitious in terms of time and how much users will need to do. We may have to make some tweaks after piloting the test.

**Comment by jaclyn-taroni** [comment]
For Ensembl ID conversion, it should be okay for users to pick out an experiment. However, it may make sense to restrict which organisms it should come from because the annotation packages do not exist for every organism. I suspect there's a lot of overlap between organisms we can generate QN targets for and those that have the appropriate annotation package.

**Comment by jaclyn-taroni** [comment]
For differential expression example, we should pick out the dataset for them so that we can pick a (relatively) straightforward comparison since time is a concern.

**Comment by jaclyn-taroni** [comment]
Everything else LGTM -- let me know if you need anything @dvenprasad

**Comment by dvenprasad** [comment]
@jaclyn-taroni 
> Is generating a CLS file in scope?
No, I want to pilot it and then see if we can include it. Users being able to successfully load the module is a little bit out of our control, especially since we don't (and also probably shouldn't) want to write a tutorial on how to use GenePattern Notebooks.

**Comment by jaclyn-taroni** [comment]
Gotcha - then the relative complexity of the experiment is less important

**Comment by cansav09** [comment]
Is this also the order you will have them do the tasks then? ie, scenario 1 first, etc.

**Comment by dvenprasad** [comment]
Yeah that is the order.

**Comment by jaclyn-taroni** [comment]
We're going to start running these.
