### ISSUE TITLE
Ortholog mapping notebook (temporarily?) won't render because of problem with HCOP data download

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#439]
### Background

The rendering upon merge step is failing with the following on the `03-rnaseq/ortholog-mapping_rnaseq_01_ensembl.Rmd` notebook:

```
trying URL 'ftp://ftp.ebi.ac.uk/pub/databases/genenames/hcop/human_mouse_hcop_fifteen_column.txt.gz'
Quitting from lines 223-232 (ortholog-mapping_rnaseq_01_ensembl-tmp-torender.Rmd) 
Error in download.file(paste0("ftp://ftp.ebi.ac.uk/pub/databases/genenames/hcop/",  : 
  cannot open URL 'ftp://ftp.ebi.ac.uk/pub/databases/genenames/hcop/human_mouse_hcop_fifteen_column.txt.gz'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> download.file
```

### Problem

I _believe_ this may only be temporary because the FTP server isn't available. You can't access the files using this page either: https://www.genenames.org/tools/hcop/ 

However, I'll note that the download is now called 16 columns instead of 15 columns. 

### What are the recommended next steps?

For now, my recommendation is to wait a day or so and try again. If the issue isn't temporary, we should find another source of data (or means/package) for ortholog mapping. If that proves to be too much work in a short time frame, we might consider temporarily removing this example from GH pages.

### Is there a particular timeframe for this issue?

We want to make sure some solution is in place this week since it prevents this notebook from rendering.

**Comment by jashapiro** [comment]
> However, I'll note that the download is now called 16 columns instead of 15 columns.

On the website it still looks like 15 columns to me? The 16 column table is the *all* human orthologs, with the extra column presumably species?

I just confirmed that <http://ftp.ebi.ac.uk/pub/databases/genenames/hcop/human_mouse_hcop_fifteen_column.txt.gz> works in the browser, so perhaps the solution could be as easy as substituting `http` for `ftp`.

**Comment by jaclyn-taroni** [comment]
You're right, I was looking at the wrong file based on how we _used to_ use the `hcop` package. We can probably make the `ftp` -> `http` change on #436.

**Comment by jashapiro** [comment]
Updated in https://github.com/AlexsLemonade/refinebio-examples/pull/436/commits/4617b73a69dfc155a3da4604d8ab9b4c601576d5

**Comment by jaclyn-taroni** [comment]
This has been resolved (for now 😱 ).
