### ISSUE TITLE
Create Homepage for Refinebio Examples

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#452]
When @dvenprasad performed usability testing, she mentioned that the examples needed a home page. This is a placeholder issue intended to track that addition; it may be edited to be more detailed or it might be better to break things up into multiple issues.

Because there are some examples-related frontend issues in this dev sprint, we may want to get more details down this sprint or the next.

I'm going to assign @dvenprasad for the moment.

**Comment by dvenprasad** [comment]
Copy: 
> Explore a variety of example analyses like clustering, differential expression, pathway analysis, etc., for [refine.bio](http://refine.bio) datasets.
> 
> How to use these examples
> 
> These examples are available as R notebooks (.Rmd) and can be modified for your [refine.bio](http://refine.bio) dataset.
> 
> - Set up: The examples are written in R and use a variety of libraries. Get started by installing the required tools and libraries.
> - Download and follow along an example analyses: You can use the refine.bio dataset that we use in analysis or you can use a different refine.bio dataset, relevant to your research interests.
> 
> 
> **RNA-seq Examples** 
> 
> Clustering
> 
> Diff expression - 
> 
> Dimension reduction
> 
> Pathways analysis
> 
> **Microarray Examples**
> 
> Clustering
> 
> Diff expression - 
> 
> Dimension reduction
> 
> Pathways analysis

@cansavvy for pathway, dimension reduction, and differential expression(microarray) which of the examples should we highlight? 

Also, here's a rough layout for the page. We can tweak it to whatever is feasible with the platform we are using. I have just used random plot images, we should replace them with appropriate ones (kudos to @cansavvy for showing the plots idea) 

![rbio-examples-homepage](https://user-images.githubusercontent.com/15315514/110388642-60c1d280-8031-11eb-957b-10b969ae8ffc.png)

**Comment by cansavvy** [comment]
I think the ones you mentioned here are fine: https://github.com/AlexsLemonade/refinebio-frontend/issues/926#issuecomment-790870534

We can get you the png’s of those plots so they can be dropped right in there. We also may want some blurbs underneath each of those example titles so people know what they are getting into. (I can write those when you are ready).

**Comment by jashapiro** [comment]
Probably better not to have the main image be a volcano plot with no significant results, lest we give people the sads.

**Comment by cansavvy** [comment]
> Probably better not to have the main image be a volcano plot with no significant results, lest we give people the sads.

Oh yes 100.

**Comment by dvenprasad** [comment]
@cansavvy 
>We can get you the png’s of those plots so they can be dropped right in there. We also may want some blurbs underneath each of those example titles so people know what they are getting into. (I can write those when you are ready).

Okay cool. Feel free to edit my comment above and drop in the blurbs. I think @davidsmejia is gonna take over at some point so would be good to have all the copy in one place

Also, which one of the dimension reduction methods should we highlight?

**Comment by cansavvy** [comment]
Going to drop the respective PNGs in the comment above. If we need higher res, we can do that.
