### ISSUE TITLE
User issue: Download for RNA-seq differential expression Rmd file is 404ing

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#473]
### Which example or page does this problem or question pertain to?

This is a user-reported (via an email to the requests address) related to the RNA-seq differential expression example.

### Report the problem you encountered or ask a question

The HTML version / GitHub pages is working: https://alexslemonade.github.io/refinebio-examples/03-rnaseq/differential-expression_rnaseq_01.html

The problem is that the link to download the file is 404ing: https://alexslemonade.github.io/refinebio-examples/03-rnaseq/differential_expression_rnaseq_01_rnaseq.Rmd

I wonder if this applies to multiple notebooks, though. That's the first thing we should look at.

**Comment by jashapiro** [comment]
A quick investigation says it is not _all_ pages... I haven't yet found another that fails.

**Comment by jashapiro** [comment]
closed by #476
