### ISSUE TITLE
Link to a notebook 404ing 

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-examples#478]
### Background

Was looking at the feedback form for refine.bio examples

### Problem

<img width="547" alt="Screen Shot 2022-07-26 at 5 15 45 PM" src="https://user-images.githubusercontent.com/15315514/181113892-041ca534-2d78-4aa4-9db2-6066f6776321.png">

### Next steps

Fix the link and then email the respondant.

**Comment by jashapiro** [comment]
I think we solved this one with https://github.com/AlexsLemonade/refinebio-examples/pull/477, and the respondant was emailed.

**Comment by jashapiro** [comment]
Actually, we should check that it was the same person, as that issue, #473, was from an email to requests@ccdl.

**Comment by dvenprasad** [comment]
yeah, it's the same person. Gonna close this issue as a duplicate then
