### ISSUE TITLE
Fix GenePattern notebook links 

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/refinebio-examples#48]
- Fix GenePattern notebook links including CLSFileCreator link.
- Link to GenePattern Notebook instead of the preview
- Link notebook links to rendered notebooks

**Comment by jaclyn-taroni** [comment]
I believe 
> Link notebook links to rendered notebooks

refers to the `*.nb.html` files that are rendered by GitHub pages rather than GenePattern notebooks and is covered by #54

**Comment by cansav09** [comment]
Do you want me to delete this one then since it's covered by the later issue?

**Comment by jaclyn-taroni** [comment]
No longer relevant
