### ISSUE TITLE
MRAN will be retired July 1, 2023

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#481]
See: https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161

I expect that may impact how we manage dependencies in the Docker image, as that's what the Rocker base image uses. For now, I think it is sufficient to note this issue if we return to development in this repo.

**Comment by jashapiro** [comment]
This Docker image is based on R 4+, which uses https://github.com/rocker-org/rocker-versioned2, which is based on the Posit Package Manager (nee RStudio Package manager), so we should be fine here!
