### ISSUE TITLE
Buff up the main README page

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/refinebio-examples#49]
Based on the recommendations explained in person by @dvenprasad, here's a main list things that need to be made to the main README. This is partially adapted from the [notion link](https://www.notion.so/Examples-Cog-Walkthrough-fa521cd336164a2483a998f6b8c27fb1) provided by @dvenprasad 

### More set up info
- [x] Add connection to training-modules
- [x] Add more set up (links to installation of RStudio and etc)
- [x] What packages are used throughout? `tidyverse`

### More GenePattern background info: 
- [x] Fix links #48 
- [x] Add more context about how the notebooks are designed to be used
- [x] Give them a heads up that they will need to login/create an account if they use the GenePattern notebooks

### More info on modifying the notebooks
- [x] Add instructions about how to use/modify the notebooks on your own data
- [x] Note about `Gene` column label not always being in the download files. `X1`
       (also determine the pattern for that and why that happens)
- [x] Add blurb recommending moving their own data in the data folder of the example

**Comment by dvenprasad** [comment]
Before we add a note about Gene column label, we should figure out if it can be fixed.

**Comment by cansav09** [comment]
@Miserlou says the Gene column label will be fixed so this won't be a thing anymore. This may mean however, we should either re-download the datasets after he fixes this, or just artificially put the "Gene" name on all of them. What do you think, @jaclyn-taroni?

**Comment by cansav09** [comment]
In our in person conversation, we've decided after the changes are deployed, we will re-download the datasets we need for this repository.

**Comment by jaclyn-taroni** [comment]
The last comment is now tracked in #65

**Comment by cansav09** [comment]
This is now addressed by #63
