### ISSUE TITLE
Upload create_gct_file.R to S3 and update when changes are pushed to master

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#81]
### Context

To make refine.bio data compatible with GenePattern, which requires a particular file format, we've included a script that takes a refine.bio TSV and outputs a GCT file. 

This script is currently located in the `scripts` folder. We explain how to use this script in the README for relevant fields (see: https://github.com/AlexsLemonade/refinebio-examples/tree/master/differential-expression#create-a-gct-file):

> #### Create a GCT file
> Convert a gene expression tab separated values (TSV) file provided into a 'gene cluster text' (GCT) file for use in GenePattern. In order to create a GCT formatted file from a TSV refine.bio data file, download the [create_gct_file.R](https://github.com/AlexsLemonade/refinebio-examples/blob/master/scripts/create_gct_file.R) script.

The link above is to https://github.com/AlexsLemonade/refinebio-examples/blob/master/scripts/create_gct_file.R

A user like myself may know how to `wget` this file. For the intended users, the only instructions we have essentially assume that they will have downloaded the entire repository and that may be unnecessarily if using GenePattern.

In addition, we've designed other modules to be self-contained (e.g., each has its own `data` folder) so that downstream users could potentially delete local copies of the modules they are not using and/or move the modules they are using outside of the overarching GitHub repository structure. 

### Problem or idea

Ideally, the link to the Rscript in the relevant READMEs (the `differential-expression` example quoted above and `clustering`) would download the latest version of that script and users could put a local copy wherever they want. I believe this would make this easier to use for the intended audience.

@arielsvn suggested the following:
- Sync this file to S3
- Update the file on S3 anytime changes to this file are pushed to master

### Next steps

@arielsvn @kurtwheeler do you have ideas about how we would accomplish this and how complex it would be to implement?

**Comment by cgreene** [comment]
How long does it take to create a GCT file from the TSV that refine.bio produces? And should we just make it one of the files that gets bundled up?

**Comment by jaclyn-taroni** [comment]
Question for @cansav09 ☝️

**Comment by jaclyn-taroni** [comment]
> And should we just make it one of the files that gets bundled up when a user downloads data from refine.bio?

It is currently unclear to me what proportion of users would use this feature and I could see a scenario where having the additional file is confusing (cc @dvenprasad)

**Comment by cansav09** [comment]
> How long does it take to create a GCT file from the TSV that refine.bio produces? And should we just make it one of the files that gets bundled up when a user downloads data from refine.bio?

I don't *think* this is necessary. The only salient application for the GCT files is for using them with Gene Pattern notebooks. The refine.bio-examples encourage people to use GenePattern if they aren't comfortable with command line or R. the `create_gct_file.R` is a thing to help those users get their data ready for GenePattern.

**Comment by kurtwheeler** [comment]
What's the benefit to putting this file on S3 instead of just having the script download the file directly from github using: `wget https://raw.githubusercontent.com/AlexsLemonade/refinebio-examples/master/scripts/create_gct_file.R`?

**Comment by cgreene** [comment]
I still wonder if there's a downside to just distributing GCT files in addition to TSV files. If we think that our least technically proficient users would be the ones who want them and they are easy/quick to make and don't take up much storage, it seems like distributing them is the best overall solution.

**Comment by cansavvy** [comment]
I think with the revamps to this repo #106 we are/should be moving away from shuttling people over to GenePattern modules (and the associated GCT file items). This was more of a thing we did in the beginning because we new that our materials would not be approachable to many users and we didn't really have the time to "ease" them into the analyses with more foundational information. 

Now we are adding more "getting started" instructions (#109) which we can provide support for (unlike after we shuttle them to GenePattern). So I think we should drop the GenePattern shuttling (which includes the GCT file creation -- which the format of is horrible anyway). Does this make sense to everyone? If yes, I will close this issue.
