### ISSUE TITLE
Users should obtain example data via the regenerate files mechanism

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#84]
### Context 

Related to: AlexsLemonade/refinebio-frontend#633, https://github.com/AlexsLemonade/refinebio-docs/issues/99, https://github.com/AlexsLemonade/refinebio-frontend/issues/636

We've designed the `Share` and `Regenerate Files` functionality of refine.bio to facilitate dataset sharing. Our examples should follow this model.

### Idea and Solution

This ticket has two components:

1. Remove any data tracked with git from the repository. 
2. Replace that information with a link to a shared dataset. This information is probably best served in a "Data Requirements" section in each module's README. 

Number two above is a bit trickier than it may seem. Specifically, notebooks in a module expect metadata and gene expression data to be in the `data` folder and we've generally ignored the JSON files. 

I'm thinking it will go something like: Follow the link > Regenerate files > Enter email and accept T&C > Download dataset via your email from the refine.bio mail robot > Unzip data in the top-level directory of a module > rename folder to `data` ?

We'll also have to pay special attention to the larger datasets that used to be zipped up. The notebooks have steps for unzipping them that need to get taken out.

#### We need to do this for the following modules:

- [ ] Clustering (@cansav09)
- [ ] Differential expression (@cansav09)
- [ ] Dimension reduction (@cansav09)
- [ ] Ensembl ID conversion (@cansav09)
- [ ] QN your own data (@jaclyn-taroni)
- [ ] Ortholog mapping (@jaclyn-taroni)
- [ ] Pathway analysis (@jaclyn-taroni)
- [ ] Validate differential expression (@cansav09)
- [ ] Batch correction (@cansav09)

**Comment by jaclyn-taroni** [comment]
@dvenprasad I think this is likely to cause a bit of friction, so would love to get your thoughts on what I outlined above.

**Comment by jaclyn-taroni** [comment]
Note that https://github.com/AlexsLemonade/refinebio-docs/issues/99 added an explanation for why regenerated datasets may have different values. If the underlying values in the dataset are slightly different, it stands to reason that the results of any analysis may look slightly different for a user locally. (Setting package versions issues aside for the moment.) Wondering if we should mirror the language in that FAQ in the READMEs.

**Comment by dvenprasad** [comment]
I don't it's a good idea to re-structure it this way because it is going to take much longer for them to get to the part they want (or part that is promised by the CTAs). The amount of investment needed from the user to follow along increases. They have to do more before they see value. 

Also, one the use cases is 'See what you can do while you wait for your dataset' and having them download the example dataset would make them wait some more.

**Comment by jaclyn-taroni** [comment]
Do we then say something about not distributing this data + link the T&C ?

**Comment by dvenprasad** [comment]
Can we mark the stuff in the data folder as not for scientific use or something similar and link them to the experiment on refine.bio to download if they want to use it for research?

**Comment by jaclyn-taroni** [comment]
@cgreene what do you think?

**Comment by jaclyn-taroni** [comment]
Put T&C in every data folder, link from main README, link from every example
> In using these data, you are agreeing to the T&C

**Comment by jaclyn-taroni** [comment]
Opted to open #85
