### ISSUE TITLE
Add terms and conditions

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#85]
We need a link to T&C in the main README and to state 
> In using these data, you agree to our terms and conditions.

1. A terms and condition markdown file needs to be placed in each module's `data` folder.
2. A link and the above statement in each module's README.

#### We need to do this for the following modules:

- [x] Clustering (@cansav09)
- [x] Differential expression (@cansav09)
- [x] Dimension reduction (@cansav09)
- [x] Ensembl ID conversion (@cansav09)
- [x] QN your own data (@jaclyn-taroni)
- [x] Ortholog mapping (@jaclyn-taroni)
- [x] Pathway analysis (@jaclyn-taroni)
- [x] Validate differential expression (@cansav09)
- [x] Batch correction (@cansav09)

**Comment by cansav09** [comment]
Although the batch-correction module is not merged yet, [I did add the TC statement and TC markdown to its own branch](https://github.com/AlexsLemonade/refinebio-examples/pull/82/commits/faabd2e21b5f154e386af5789f3b880207f987d0).
