### ISSUE TITLE
`tibble::columns_as_rownames` in differential expression notebook

### ISSUE THREAD

**Issue by cansav09** [AlexsLemonade/refinebio-examples#90]
@dvenprasad found in the usability evals that they had an error come up with`as.data.frame != TRUE` `tibble::columns_as_rownames`. Need to investigate and fix this.

**Comment by cbethell** [comment]
@dvenprasad sent a screen shot of the error and it appears that `df <- as.data.frame(GSE93597) dplyr:: '%>%'` was introduced incorrectly with improper use of the Magrittr pipe, before the attempted execution of `tibble::column_to_rownames("Gene")`. The referenced screenshot is below. 

![screen_shot_2019-07-09_at_3 52 31_pm](https://user-images.githubusercontent.com/43576623/60919840-b6dee100-a264-11e9-9eaa-4fdaa585f995.png)

**Comment by jaclyn-taroni** [comment]
@cbethell would you say that this error is likely to arise again when folks use this notebook or do you think it was a one-off/will happen infrequently?

**Comment by cbethell** [comment]
@jaclyn-taroni it looks to me like a one-off/infrequent case, I tested the code from each section of the notebook in a separate script and they all executed without error.

**Comment by jaclyn-taroni** [comment]
👍 please feel free to close this issue in that case!

**Comment by cbethell** [comment]
Great, I'll do that now!
