### ISSUE TITLE
[Idea] Port over examples to use bookdown

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#92]
Not all of our users will be familiar with GitHub and our use of GitHub requires a lot of repetition of text. Would using bookdown be "friendlier?"

Here's an excellent example: [Claus O. Wilke's _Fundamentals of Data Visualization_](https://serialmentor.com/dataviz/)

#### Relevant links

* [bookdown website](https://bookdown.org/)
* [GitHub](https://github.com/rstudio/bookdown)

**Comment by dvenprasad** [comment]
The problem with Github is that it presents the files first and then the README. People not familiar with Github are not likely to scroll down. Also it's so intimidating.  Explore bookdown.... we might not have repeat as many things like we do in the READMEs, maybe will be even easier to navigate.

**Comment by cansavvy** [comment]
I think we've decided against this because of the folder structure constraints See #107 for full discussion. I'm going to close this. If things change and we decide to return to bookdown for some reason, we can reopen it.
