### ISSUE TITLE
API steps in normalize-own-data need to be updated 

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#96]
Related to: https://github.com/AlexsLemonade/refinebio-docs/pull/119

**Comment by jaclyn-taroni** [comment]
Was this closed by #121?

**Comment by cansavvy** [comment]
> Was this closed by #121?

I don't believe so, but I suppose to be able to answer that question more accurately; what parts of the `normalize-own-data` need to be updated?

**Comment by jaclyn-taroni** [comment]
Obtaining the QN target from the API. We wrote the example before the API was versioned. See this change from the referenced docs PR: https://github.com/AlexsLemonade/refinebio-docs/pull/119/files#diff-1888225f52458a757410c236ce3c46f0L284

I assume this can be closed because of this comment https://github.com/AlexsLemonade/refinebio-examples/pull/121#issuecomment-656300306 referencing https://github.com/AlexsLemonade/refinebio-examples/pull/121/commits/cf269f338302e3a2d193357c979eac16c1019ce8.
