### ISSUE TITLE
Recommendations from 2019 evaluations

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-examples#97]
In mid-2019, @dvenprasad did a series of usability evaluations. This epic is to track issues related to recommendations that stem from that series of evaluations.

**Comment by jaclyn-taroni** [comment]
@cansavvy do you want to close this now that you opened #106? I think they're designed to track the same thing.

**Comment by cansavvy** [comment]
Yes. I was thinking that.

**Comment by cansavvy** [comment]
This epic issue has been subsumed by #106
