### ISSUE TITLE
Add Mus musculus as an example to illustrate change in annotation package

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-examples#98]
In the notebook for converting Ensembl IDs to Gene Symbols, write another example after human. 
Mouse would be good since it would cover our top 3 organisms. 
Something along the line : `For Mus musculus, Mm would be used` 

<img width="806" alt="Screen Shot 2020-05-29 at 9 07 13 AM" src="https://user-images.githubusercontent.com/15315514/83263293-5b735580-a18c-11ea-8dce-37e0bba60971.png">

**Comment by cansavvy** [comment]
Since #113 used mouse annotation, and has been merged, this can be closed!
