### ISSUE TITLE
Add inline comments in notebooks where users need to replace code

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-examples#99]
Users didn't always feel confident about what they needed to replace. Users tended to skim through the comments before the code blocks and often missed what they need to do. 

Add inline comments like
`Replace path with path to your data file`
`Replace with your organism` 
So it explicit what they are expected to do. 

<img width="838" alt="Screen Shot 2020-05-29 at 9 19 26 AM" src="https://user-images.githubusercontent.com/15315514/83264039-88743800-a18d-11ea-96de-31f31e05efa7.png">

**Comment by cbethell** [comment]
I can get started with this ticket 👍 I spoke to Candace and we both believe this is probably a good start for me with this repo.
